// ===================================================================
// MRCS PART A — Paper 2, Section 2: PERIOPERATIVE MANAGEMENT (35 marks)
// plus the cross-cutting BASIC SURGICAL SKILLS module (Module 3), which is
// examined in both Part A Paper 2 and the Part B OSCE.
// ===================================================================

window.MRCS_PERIOP = [
  {
    id: "periop",
    name: "Perioperative Management",
    short: "Perioperative",
    icon: "🏥",
    paper: "paper2",
    marks: 35,
    itemNoun: "topics",
    fieldLabels: ["📋 Core knowledge", "🔬 Assessment & investigation", "💊 Management"],
    blurb: "Thirty-five marks and the most clinically familiar section in the paper — this is the ward and theatre work you already do. Postoperative care alone is eight marks, more than pharmacology, microbiology and imaging combined.",
    conditions: [

      // ---------------- PREOPERATIVE (7 marks) ----------------
      {
        id: "pe_pre_assessment",
        cluster: "Preoperative assessment & management (7 marks)",
        name: "Preoperative assessment and risk scoring",
        keyFacts: "American Society of Anesthesiologists grades: I healthy, II mild systemic disease, III severe systemic disease, IV severe systemic disease that is a constant threat to life, V moribund and not expected to survive without the operation, VI brain-dead organ donor. E is appended for emergency.",
        presentation: "Assessment covers the indication for surgery, the patient's fitness, their comorbidity, their medication, their functional reserve and their own priorities. Functional capacity below four metabolic equivalents — being unable to climb a flight of stairs without stopping — identifies increased perioperative risk and should prompt further assessment.",
        investigations: "Investigations should be targeted, not routine: NICE guidance recommends tests based on grade of surgery and American Society of Anesthesiologists grade, so a fit young person having minor surgery needs none. Risk scores include the Revised Cardiac Risk Index, P-POSSUM for surgical mortality prediction, and the National Emergency Laparotomy Audit risk calculator. Cardiopulmonary exercise testing quantifies reserve before major surgery, with an anaerobic threshold below about 11 mL/kg/min indicating higher risk.",
        treatment: "Optimise what can be optimised: anaemia (with intravenous iron where appropriate rather than transfusion), glycaemic control, blood pressure, heart failure, respiratory disease, nutrition and smoking cessation. Prehabilitation with exercise, nutrition and psychological preparation improves outcomes before major surgery. Give the patient a realistic account of risk in numbers they can understand, and document it.",
      },
      {
        id: "pe_pre_consent",
        cluster: "Preoperative assessment & management (7 marks)",
        name: "Consent, capacity and shared decision making",
        keyFacts: "Since Montgomery v Lanarkshire (2015), the test of what must be disclosed is what a reasonable patient in that position would want to know, not what a reasonable body of doctors would disclose — the material risks and the reasonable alternatives, including doing nothing.",
        presentation: "Valid consent requires that the patient has capacity, is appropriately informed, and gives consent voluntarily. Consent should be taken by someone capable of performing the procedure or specifically trained to take consent for it, and ideally not immediately before surgery.",
        investigations: "Capacity under the Mental Capacity Act 2005 requires the ability to understand the information, retain it, weigh it in the balance and communicate a decision. Capacity is decision-specific and time-specific, and is presumed unless demonstrated otherwise; an unwise decision is not evidence of incapacity. Children under 16 may consent if Gillick competent; those aged 16 and 17 are presumed competent to consent.",
        treatment: "If a patient lacks capacity, act in their best interests, taking account of any advance decision to refuse treatment, a lasting power of attorney for health and welfare, or a court-appointed deputy, and consult those close to them. Use an independent mental capacity advocate where there is no one to consult for serious decisions. Emergency treatment necessary to save life may proceed under the doctrine of necessity. Document the discussion, the risks quoted and the alternatives offered.",
      },
      {
        id: "pe_pre_comorbid",
        cluster: "Preoperative assessment & management (7 marks)",
        name: "Management of comorbidity and preoperative prescribing",
        keyFacts: "Drugs to continue on the day of surgery: beta-blockers, statins, antiepileptics, inhalers, thyroid replacement and corticosteroids. Drugs commonly withheld: angiotensin-converting enzyme inhibitors, angiotensin receptor blockers, diuretics and sodium-glucose cotransporter 2 inhibitors.",
        presentation: "Cardiac disease, respiratory disease, diabetes, renal impairment, liver disease, obesity, obstructive sleep apnoea, frailty and cognitive impairment all change perioperative risk and management. Frailty is an independent predictor of poor outcome and should be measured, for example with the Clinical Frailty Scale.",
        investigations: "Identify the patient on long-term steroids who will need supplementation, the anticoagulated patient who needs an individualised plan, the patient with a coronary stent whose antiplatelet therapy must not be interrupted without cardiology discussion, and the patient with a difficult airway. Screen for obstructive sleep apnoea with the STOP-BANG questionnaire.",
        treatment: "Discuss high-risk patients at a multidisciplinary preoperative meeting. Anticoagulation planning balances thrombotic against bleeding risk: direct oral anticoagulants are timed according to renal function and procedural bleeding risk; warfarin bridging with therapeutic low molecular weight heparin is reserved for the highest thrombotic risk. Antibiotic and venous thromboembolism prophylaxis should be prescribed at the time of listing so they are not forgotten.",
      },
      {
        id: "pe_pre_fasting",
        cluster: "Preoperative assessment & management (7 marks)",
        name: "Fasting, day surgery and enhanced recovery",
        keyFacts: "Fasting rules are 6 hours for solids, 6 hours for formula milk, 4 hours for breast milk and 2 hours for clear fluids — and prolonged unnecessary fasting causes dehydration, hypoglycaemia and distress without adding safety.",
        presentation: "Day surgery is now the default for many procedures. Selection depends on the procedure, the patient's comorbidity being stable rather than absent, and social factors — a responsible adult at home for 24 hours and reasonable access to help. Discharge criteria include stable observations, tolerating fluids, adequate analgesia, ability to mobilise and, for some procedures, passing urine.",
        investigations: "Assess suitability at preoperative assessment rather than on the day. Obstructive sleep apnoea, poorly controlled diabetes, high body mass index with comorbidity and complex anticoagulation may make day surgery unsuitable. Anticipate the common causes of unplanned admission: pain, nausea and vomiting, bleeding and urinary retention.",
        treatment: "Enhanced recovery after surgery combines preoperative counselling and carbohydrate loading, avoidance of prolonged fasting and bowel preparation where not needed, regional or opioid-sparing analgesia, goal-directed fluid therapy, minimally invasive surgery, avoidance of drains and tubes, early feeding and early mobilisation. The benefits are shorter stay and fewer complications, and the programme works because it is applied as a whole rather than piecemeal.",
      },
      {
        id: "pe_pre_prophylaxis",
        cluster: "Preoperative assessment & management (7 marks)",
        name: "Antibiotic and thromboprophylaxis",
        keyFacts: "Prophylactic antibiotics are a single dose within 60 minutes of incision, repeated only for prolonged surgery or major blood loss. Continuing them after 24 hours increases resistance and Clostridioides difficile without reducing surgical site infection.",
        presentation: "Antibiotic prophylaxis is indicated for clean surgery involving prosthetic material, all clean-contaminated surgery, and contaminated or dirty surgery (where it becomes treatment). The agent must cover the flora expected at that site. Venous thromboembolism risk assessment is mandatory on admission and at 24 hours.",
        investigations: "Assess bleeding risk alongside thrombotic risk before prescribing pharmacological prophylaxis. Contraindications include active bleeding, a recent haemorrhagic stroke, severe thrombocytopenia and planned neuraxial anaesthesia within the relevant window. Check renal function before low molecular weight heparin dosing.",
        treatment: "Mechanical prophylaxis is antiembolism stockings (contraindicated in peripheral arterial disease) and intermittent pneumatic compression. Pharmacological prophylaxis is usually low molecular weight heparin. Extended prophylaxis for 28 days follows major abdominal or pelvic cancer surgery, and 35 days follows hip arthroplasty. Early mobilisation and adequate hydration remain part of prophylaxis.",
      },
      {
        id: "pe_pre_immunisation",
        cluster: "Preoperative assessment & management (7 marks)",
        name: "Immunisation, occupational health and the high-risk patient",
        keyFacts: "Vaccination before elective splenectomy should be given at least two weeks preoperatively; after emergency splenectomy it is usually given about two weeks postoperatively when the immune response is better.",
        presentation: "Asplenic and hyposplenic patients require pneumococcal, meningococcal and Haemophilus influenzae type b vaccination, annual influenza vaccination, antibiotic prophylaxis, a patient alert card and education about the risk of overwhelming post-splenectomy infection and travel-related infection.",
        investigations: "Surgeons must be immune to hepatitis B with documented seroconversion; those performing exposure-prone procedures are subject to health clearance requirements. Assess tetanus immunisation status in every wound, and give immunoglobulin as well as vaccine for tetanus-prone wounds in the inadequately immunised.",
        treatment: "Manage sharps injuries immediately: wash, encourage bleeding, report, risk-assess and take baseline serology, with human immunodeficiency virus post-exposure prophylaxis started within hours if indicated. Reduce risk with double gloving, blunt needles for fascial closure, a hands-free passing technique and eye protection. Do not rely on knowing a patient's status; use universal precautions for everyone.",
      },
      {
        id: "pe_pre_frailty",
        cluster: "Preoperative assessment & management (7 marks)",
        name: "The older surgical patient and frailty",
        keyFacts: "Frailty predicts postoperative complications, length of stay and mortality better than chronological age, and it is modifiable in part through prehabilitation and comprehensive geriatric assessment.",
        presentation: "Frailty is a state of reduced physiological reserve, recognised by weakness, slow gait, exhaustion, low activity and weight loss, or measured by a scale such as the Clinical Frailty Scale. Older patients also present atypically: sepsis without fever, myocardial infarction without chest pain, and peritonitis without guarding.",
        investigations: "Assess cognition at baseline, because postoperative delirium cannot be recognised without it. Review polypharmacy, nutrition, continence, mobility, falls risk and social circumstances. Comprehensive geriatric assessment before major elective surgery reduces complications and length of stay.",
        treatment: "Involve orthogeriatric or perioperative medicine teams early, particularly for hip fracture and emergency laparotomy where their input is a measured standard. Prevent delirium with orientation, sleep hygiene, hydration, early mobilisation, spectacles and hearing aids, opioid-sparing analgesia and avoidance of anticholinergics. Discuss ceilings of treatment and resuscitation status early, honestly and with the patient wherever possible.",
      },

      // ---------------- INTRAOPERATIVE (5 marks) ----------------
      {
        id: "pe_intra_safety",
        cluster: "Intraoperative care (5 marks)",
        name: "Theatre safety, the WHO checklist and never events",
        keyFacts: "Never events include wrong-site surgery, wrong implant or prosthesis, and retained foreign object after surgery — they are largely preventable and are the reason the checklist and swab counts are mandatory.",
        presentation: "The World Health Organization Surgical Safety Checklist has three phases: sign in before induction (patient identity, site marking, allergies, airway risk, blood loss risk), time out before incision (team introductions, procedure, antibiotic prophylaxis, imaging, anticipated critical events) and sign out before the patient leaves theatre (procedure recorded, counts correct, specimen labelling, concerns for recovery).",
        investigations: "Team briefing at the start of the list and debriefing at the end are part of the same system. Effective checklist use depends on the whole team stopping and engaging, not on ticking boxes; this is why the surgeon should lead the time out. Human factors — hierarchy, distraction, fatigue, poor communication — underlie most surgical error.",
        treatment: "When something goes wrong, the response is to stabilise the patient, inform the consultant, document factually, report through the incident system and comply with the duty of candour by being open with the patient and apologising. Swab, needle and instrument counts are the responsibility of the whole team but the surgeon must not close until told the count is correct. Retained items are investigated as serious incidents.",
      },
      {
        id: "pe_intra_positioning",
        cluster: "Intraoperative care (5 marks)",
        name: "Patient positioning, pressure care and nerve injury",
        keyFacts: "Lithotomy risks common peroneal nerve injury at the fibular head; the arm abducted beyond 90 degrees risks brachial plexus injury; and prolonged pressure on the ulnar nerve at the elbow is the commonest anaesthetic nerve injury claim.",
        presentation: "Positions include supine, Trendelenburg, reverse Trendelenburg, lithotomy, lateral, prone and the Lloyd-Davies position. Each carries specific risks to nerves, pressure areas, eyes and physiology — the prone position risks eye and airway complications, and steep Trendelenburg raises intracranial and intraocular pressure and impairs ventilation.",
        investigations: "Assess pressure risk before surgery in the frail, the obese, the diabetic and those with peripheral vascular disease, and for any operation expected to exceed a few hours. Document the position and the padding used. New postoperative weakness or numbness should be examined and documented promptly.",
        treatment: "Prevent injury by padding bony prominences and vulnerable nerves, keeping joints in neutral, avoiding excessive abduction or external rotation, using gel pads and heel protection, protecting the eyes, and repositioning during long operations. Compartment syndrome of the leg can follow prolonged lithotomy. Involve the whole team in transfers and positioning, and check again after draping.",
      },
      {
        id: "pe_intra_diathermy",
        cluster: "Intraoperative care (5 marks)",
        name: "Diathermy, lasers and tourniquets",
        keyFacts: "Monopolar diathermy passes current through the patient to a return plate and must never be used on an appendage with a narrow pedicle; bipolar diathermy passes current only between the forceps tips and is safe in those situations.",
        presentation: "Diathermy uses high-frequency alternating current (about 300 kHz to 3 MHz) to heat tissue: a continuous waveform cuts, a pulsed waveform coagulates. Risks are burns at the return plate, alternative site burns, channelling injury, interference with pacemakers, surgical smoke and ignition of alcoholic skin preparation.",
        investigations: "Check the return electrode placement over well-perfused muscle away from bony prominences, scars, metal implants and hair. In a patient with a cardiac implantable electronic device, plan in advance with cardiology: use bipolar where possible, position the plate so the current path avoids the device, and have external pacing and defibrillation available.",
        treatment: "Tourniquet use: exsanguinate first, apply a wide cuff over padding, record the pressure and time, keep inflation under about 2 hours where possible, and avoid in peripheral vascular disease, sickle cell disease and infection. Post-tourniquet syndrome causes swelling, pain and weakness. Laser safety requires eye protection for all, controlled access, matt instruments and awareness of plume hazards. Never place alcoholic preparation where it can pool, and allow it to dry before using diathermy.",
      },
      {
        id: "pe_intra_anaesthesia",
        cluster: "Intraoperative care (5 marks)",
        name: "Principles of anaesthesia and monitoring",
        keyFacts: "Minimum monitoring standards for anaesthesia are pulse oximetry, capnography, electrocardiography, non-invasive blood pressure and inspired oxygen concentration; capnography is also mandatory whenever an airway device is in place, including in intensive care and during transfer.",
        presentation: "General anaesthesia comprises hypnosis, analgesia and, where required, muscle relaxation. Regional anaesthesia includes spinal, epidural and peripheral nerve blocks. Rapid sequence induction is used where there is aspiration risk: preoxygenation, a predetermined induction agent and rapid-onset muscle relaxant, with or without cricoid pressure.",
        investigations: "Airway assessment uses the Mallampati score, thyromental distance, mouth opening, neck movement and previous difficulty. Predictors of difficulty include obesity, obstructive sleep apnoea, a short neck, limited mouth opening, previous neck radiotherapy or surgery and rheumatoid arthritis with atlantoaxial instability. Invasive monitoring is used for major surgery: arterial line for beat-to-beat pressure and gases, central venous access for drugs and pressure, and cardiac output monitoring for goal-directed therapy.",
        treatment: "Recognise and be able to help with the intraoperative emergencies: anaphylaxis, malignant hyperthermia, laryngospasm, high spinal block, local anaesthetic systemic toxicity, massive haemorrhage and cardiac arrest. Know where the difficult airway trolley and the lipid emulsion are kept. Communicate anticipated blood loss and critical steps to the anaesthetist during the time out and as the operation proceeds.",
      },
      {
        id: "pe_intra_bypass",
        cluster: "Intraoperative care (5 marks)",
        name: "Cardiopulmonary bypass and special intraoperative situations",
        keyFacts: "Cardiopulmonary bypass causes a systemic inflammatory response, haemodilution, platelet dysfunction and consumption of coagulation factors, so bleeding after bypass is multifactorial rather than purely surgical.",
        presentation: "Bypass diverts blood from the venous circulation through an oxygenator and pump back into the arterial system, allowing a still, bloodless field. Myocardial protection uses cardioplegia and hypothermia. Complications include neurological injury, acute kidney injury, coagulopathy, systemic inflammatory response and, rarely, aortic dissection from cannulation.",
        investigations: "Anticoagulation with heparin is monitored by activated clotting time and reversed with protamine, which itself can cause hypotension and anaphylactoid reactions. Temperature, acid-base status and haematocrit are managed throughout. Postoperative bleeding is assessed against defined chest drain output thresholds that trigger re-exploration.",
        treatment: "Surgery in the pregnant patient: avoid the supine position after 20 weeks because of aortocaval compression, involve obstetrics and paediatrics early, favour the second trimester for elective procedures, and remember that maternal resuscitation takes priority over fetal monitoring. Laparoscopy causes carbon dioxide absorption with hypercapnia, raised intra-abdominal pressure reducing venous return, and a risk of gas embolism and port-site injury.",
      },

      // ---------------- PERIOPERATIVE CARE (2 marks) ----------------
      {
        id: "pe_peri_eras",
        cluster: "Perioperative care (2 marks)",
        name: "Enhanced recovery protocols after complex surgery",
        keyFacts: "Enhanced recovery works because it is a bundle: the individual elements have small effects, but applied together they reduce complications and length of stay substantially.",
        presentation: "Core elements before surgery: counselling and expectation setting, prehabilitation, carbohydrate loading, avoidance of prolonged fasting and of routine bowel preparation. During surgery: minimally invasive technique, regional or opioid-sparing analgesia, goal-directed fluid therapy, normothermia and avoidance of drains and nasogastric tubes.",
        investigations: "Audit compliance with each element rather than only the outcome, because failure is usually a compliance problem. Measure length of stay, complications, readmission and patient-reported outcomes. Identify which elements are not being delivered and why.",
        treatment: "After surgery: early oral intake on the day of operation, early mobilisation with defined daily targets, early removal of catheters and lines, multimodal analgesia with opioid sparing, prophylaxis against nausea and vomiting, and structured daily goals shared with the patient. The patient must understand and take part in the plan — enhanced recovery is a partnership, not something done to them.",
      },
      {
        id: "pe_peri_fluid",
        cluster: "Perioperative care (2 marks)",
        name: "Perioperative fluid therapy",
        keyFacts: "The four Rs of fluid prescribing: resuscitation, routine maintenance, replacement of ongoing losses, and redistribution. Prescribing the wrong one of these causes most fluid-related harm on surgical wards.",
        presentation: "Both hypovolaemia and fluid overload are harmful: hypovolaemia causes acute kidney injury and impaired healing, while overload causes pulmonary oedema, ileus, anastomotic oedema and delayed recovery. Postoperative patients have raised antidiuretic hormone and aldosterone, so they retain sodium and water and are prone to dilutional hyponatraemia.",
        investigations: "Assess volume status with heart rate, blood pressure, capillary refill, jugular venous pressure, urine output, fluid balance charts, daily weights, and lactate. Dynamic assessment such as a fluid challenge, passive leg raise or stroke volume variation is more reliable than static central venous pressure. Check electrolytes daily in anyone on intravenous fluids.",
        treatment: "Use balanced crystalloids rather than large volumes of 0.9 per cent sodium chloride, which causes hyperchloraemic acidosis. Maintenance is approximately 25 to 30 mL/kg/day of water with about 1 mmol/kg/day each of sodium, potassium and chloride. Replace measured losses like for like: high-output stoma and small bowel losses are sodium- and bicarbonate-rich, and nasogastric losses are rich in hydrogen, potassium and chloride. Stop intravenous fluids as soon as the patient is drinking.",
      },

      // ---------------- POSTOPERATIVE (8 marks) ----------------
      {
        id: "pe_post_monitoring",
        cluster: "Postoperative care (8 marks)",
        name: "Postoperative monitoring and the deteriorating patient",
        keyFacts: "A rising National Early Warning Score, particularly a rising respiratory rate, is the earliest and most sensitive sign of postoperative deterioration — respiratory rate is the vital sign most often not recorded and most often abnormal first.",
        presentation: "Structured assessment using airway, breathing, circulation, disability and exposure. Common causes of postoperative deterioration: hypovolaemia, bleeding, sepsis, anastomotic leak, myocardial infarction, pulmonary embolism, respiratory failure and drug effects. The unwell postoperative surgical patient has a surgical cause until proved otherwise.",
        investigations: "Review the operation note, the drug chart, the fluid balance and the observation chart before examining. Investigations are guided by the assessment: full blood count, urea and electrolytes, C-reactive protein, lactate, blood gases, cultures, electrocardiogram, and cross-sectional imaging where a surgical complication is suspected. A C-reactive protein that fails to fall after day 3 to 4, or rises again, suggests a complication.",
        treatment: "Escalate early: call the registrar or consultant, and involve critical care outreach. The CCrISP approach is immediate management, full patient assessment, decision and plan, and definitive care. Do not accept a diagnosis of atelectasis or constipation in a patient who is deteriorating — look for a leak, a collection or a bleed. Timely return to theatre saves lives; delay is the commonest cause of avoidable death after surgery.",
        management: {
          def: "A[\"Deteriorating post-op patient\"]:::start --> B[\"Immediate ABCDE, oxygen, IV access, monitoring\"]:::process\nB --> C[\"Full assessment: notes, op note, charts, drugs, examination\"]:::process\nC --> D[\"Bloods, gas, lactate, cultures, ECG\"]:::process\nD --> E{\"Likely cause?\"}:::decision\nE -- \"Sepsis / leak\" --> F[\"Sepsis Six + urgent CT + senior review\"]:::danger\nE -- \"Bleeding\" --> G[\"Resuscitate, transfuse, major haemorrhage protocol\"]:::danger\nE -- \"Cardiac / PE\" --> H[\"ECG, troponin, CTPA, cardiology input\"]:::warn\nE -- \"Respiratory\" --> I[\"Physio, analgesia, CPAP, treat infection\"]:::warn\nF --> J[\"Source control: theatre or radiology\"]:::danger\nG --> J\nJ --> K[\"Critical care referral\"]:::process",
          tips: {
            "A": "A rising early warning score, especially respiratory rate, precedes collapse by hours.",
            "C": "Read the operation note before you examine — it tells you what can go wrong and where.",
            "F": "Antibiotics within one hour, but they do not replace source control of an undrained collection or leak.",
            "J": "Delay in returning to theatre is the commonest contributor to avoidable postoperative death.",
          },
        },
      },
      {
        id: "pe_post_complications",
        cluster: "Postoperative care (8 marks)",
        name: "Postoperative complications and the postoperative fever",
        keyFacts: "The classic timing of postoperative pyrexia — the five Ws: wind (atelectasis, pneumonia) days 1 to 2, water (urinary tract infection) days 3 to 5, wound days 5 to 7, walking (venous thromboembolism) days 5 to 10, and wonder drugs or collections thereafter. A fever after day 5 should raise the possibility of an anastomotic leak or collection.",
        presentation: "Classify complications as immediate (within 24 hours), early (within 30 days) and late; and as general (respiratory, cardiac, thromboembolic, renal, infective) or specific to the operation. Anastomotic leak presents with pain, tachycardia, ileus, fever, raised inflammatory markers, or simply a patient who is not progressing as expected.",
        investigations: "Examine the wound, the drains and the abdomen; review the trend in observations and inflammatory markers rather than single values. Computed tomography with contrast is the investigation of choice for suspected leak or collection, though a negative scan does not exclude a leak in the first 48 hours. Blood and urine cultures, chest radiograph and wound swabs as indicated.",
        treatment: "Wound complications: infection (open, drain and pack), haematoma, seroma, dehiscence and incisional hernia. Burst abdomen presents around day 7 to 10 with pink serous discharge and requires resuscitation, covering the wound with saline-soaked packs and return to theatre. Anastomotic leak requires resuscitation, antibiotics and source control by radiological drainage or surgery. Prevent complications with good analgesia, physiotherapy, early mobilisation, thromboprophylaxis and nutrition.",
      },
      {
        id: "pe_post_analgesia",
        cluster: "Postoperative care (8 marks)",
        name: "Postoperative analgesia",
        keyFacts: "Multimodal, opioid-sparing analgesia is the standard: paracetamol plus a non-steroidal anti-inflammatory drug where safe, plus a regional technique, with opioids as the top-up rather than the foundation.",
        presentation: "Poorly controlled pain prevents deep breathing, coughing and mobilisation, and therefore causes atelectasis, pneumonia, thromboembolism and delayed recovery. Assess pain at rest and on movement, using a simple score, and reassess after treatment.",
        investigations: "Consider the cause of new or escalating pain rather than simply increasing the dose — new severe pain after surgery may indicate a leak, ischaemia, compartment syndrome, haematoma or urinary retention. Chronic post-surgical pain is common after thoracotomy, hernia repair, mastectomy and amputation, and is more likely when acute pain is poorly controlled.",
        treatment: "Options include oral and parenteral analgesics, patient-controlled analgesia, epidural analgesia, spinal opioids, wound catheters and peripheral nerve blocks. Epidurals provide excellent analgesia but cause hypotension and urinary retention, and new back pain with neurology demands immediate imaging for haematoma or abscess. Non-steroidal anti-inflammatory drugs are avoided in renal impairment, hypovolaemia, heart failure and peptic ulcer disease. Always co-prescribe laxatives and antiemetics with opioids.",
      },
      {
        id: "pe_post_organfailure",
        cluster: "Postoperative care (8 marks)",
        name: "Detection and initial management of organ failure",
        keyFacts: "Multiple organ dysfunction syndrome is the failure of two or more organ systems, and mortality rises steeply with each additional organ — which is why early recognition and source control matter more than any specific organ support.",
        presentation: "Acute kidney injury: oliguria, rising creatinine, fluid overload, hyperkalaemia and acidosis. Respiratory failure: rising oxygen requirement, rising respiratory rate, hypercapnia. Cardiac failure: hypotension, raised jugular venous pressure, oedema. Hepatic dysfunction: jaundice, coagulopathy, encephalopathy.",
        investigations: "Acute kidney injury is staged by creatinine rise and urine output (under 0.5 mL/kg/h for 6 hours or more). Look for the three categories of cause — prerenal (hypovolaemia, sepsis, cardiac failure), renal (nephrotoxins, contrast, rhabdomyolysis) and postrenal (obstruction, blocked catheter). Always exclude obstruction with a bladder scan and ultrasound.",
        treatment: "Optimise perfusion, stop nephrotoxic drugs (non-steroidal anti-inflammatory drugs, angiotensin-converting enzyme inhibitors, aminoglycosides), relieve obstruction and treat sepsis. Indications for renal replacement therapy: refractory hyperkalaemia, refractory acidosis, refractory fluid overload, uraemic complications such as pericarditis and encephalopathy, and certain poisonings. Refer to critical care early rather than when organ support is already inevitable.",
      },
      {
        id: "pe_post_delirium",
        cluster: "Postoperative care (8 marks)",
        name: "Postoperative delirium and cognitive dysfunction",
        keyFacts: "Hypoactive delirium is commoner than hyperactive delirium and is routinely missed, because a quiet, withdrawn patient does not attract attention — screen actively rather than waiting for agitation.",
        presentation: "Acute onset, fluctuating course, inattention, disorganised thinking and altered consciousness. Distinguish from dementia (chronic, stable, attention relatively preserved) while remembering that delirium is commonest in people who already have dementia. Risk factors are age, cognitive impairment, sensory impairment, polypharmacy, and severity of illness or surgery.",
        investigations: "Screen with a validated tool such as the 4AT. Then look for the cause: hypoxia, sepsis, pain, urinary retention, constipation, electrolyte disturbance, hypoglycaemia, drugs (especially anticholinergics, benzodiazepines and opioids), alcohol or benzodiazepine withdrawal, and intracranial events. Delirium is a symptom, not a diagnosis.",
        treatment: "Treat the cause. Non-pharmacological measures first: orientation, familiar faces, spectacles and hearing aids, sleep hygiene, hydration, mobilisation, and a quiet well-lit environment. Reserve antipsychotics for severe distress or risk of harm, at the lowest dose for the shortest time, avoiding them in Parkinson's disease and Lewy body dementia. Explain delirium to the patient and family; it is frightening and often remembered.",
      },
      {
        id: "pe_post_thermo",
        cluster: "Postoperative care (8 marks)",
        name: "Thermoregulation and postoperative recovery",
        keyFacts: "Perioperative hypothermia below 36 degrees Celsius increases wound infection, bleeding, transfusion requirement, cardiac events and length of stay, and active warming is a NICE standard rather than an optional extra.",
        presentation: "Redistribution of heat from core to periphery in the first hour of anaesthesia accounts for a fall of about 1 to 1.5 degrees. Shivering increases oxygen consumption substantially and is dangerous in patients with limited cardiac reserve. Postoperative pyrexia is discussed separately, but early pyrexia within hours may reflect the inflammatory response to surgery rather than infection.",
        investigations: "Measure temperature before induction, throughout surgery and in recovery. Do not transfer a hypothermic patient to the ward without warming. Assess for causes of failure to warm, including large-volume unwarmed fluid, prolonged exposure and a cold theatre.",
        treatment: "Prevent heat loss with forced-air warming, warmed intravenous and irrigation fluids, minimised exposure and an appropriate ambient temperature. Treat shivering with warming and, if needed, low-dose pethidine or clonidine. Discharge from recovery requires stable observations, a patent airway, adequate analgesia, controlled nausea, normothermia and an appropriate conscious level.",
      },
      {
        id: "pe_post_ileus",
        cluster: "Postoperative care (8 marks)",
        name: "Ileus, nausea and gastrointestinal recovery",
        keyFacts: "Small bowel function returns within hours of laparotomy, the stomach within 24 to 48 hours and the colon within 48 to 72 hours — so the colon determines when a patient passes flatus and can eat.",
        presentation: "Postoperative ileus gives diffuse distension, absent bowel sounds, nausea and vomiting without colicky pain, and gas is seen throughout the bowel including the rectum. Mechanical obstruction gives colicky pain, a transition point on imaging and, if early after surgery, raises the possibility of an internal hernia, adhesion or technical problem.",
        investigations: "Distinguish ileus from mechanical obstruction and from anastomotic leak, which can present as a prolonged ileus. Check potassium and magnesium. Computed tomography with contrast if ileus is prolonged beyond about 5 days or if the patient is systemically unwell.",
        treatment: "Manage with nasogastric decompression if vomiting, correction of electrolytes, opioid sparing, avoidance of fluid overload, chewing gum and early mobilisation. Postoperative nausea and vomiting risk is predicted by female sex, non-smoking status, previous history and postoperative opioid use; prophylaxis uses agents from different classes. Pseudo-obstruction is treated by correcting precipitants, neostigmine under cardiac monitoring, or colonoscopic decompression, with surgery if the caecum is at risk of perforation.",
      },

      // ---------------- NUTRITION (2 marks) ----------------
      {
        id: "pe_nut_assessment",
        cluster: "Nutritional management (2 marks)",
        name: "Nutritional assessment and perioperative nutrition",
        keyFacts: "If the gut works, use it. Enteral nutrition maintains mucosal integrity, reduces bacterial translocation and has fewer septic complications and lower cost than parenteral nutrition.",
        presentation: "Malnutrition is common in surgical patients and increases infection, poor wound healing, anastomotic leak and mortality. Screen every admission with a validated tool such as the Malnutrition Universal Screening Tool, using body mass index, unplanned weight loss and acute disease effect.",
        investigations: "Albumin is a negative acute phase protein and a poor nutritional marker, although it predicts outcome. Assess weight trend, oral intake, gastrointestinal symptoms and functional status. Identify refeeding risk: body mass index under 16, weight loss over 15 per cent, negligible intake for more than 10 days, or low potassium, phosphate or magnesium before feeding.",
        treatment: "Route selection: oral supplements, nasogastric or nasojejunal feeding, gastrostomy or jejunostomy for longer-term needs, and parenteral nutrition only for intestinal failure. Requirements are approximately 25 to 30 kcal/kg/day with 0.8 to 1.5 g/kg/day of protein. Start at no more than 10 kcal/kg/day in those at refeeding risk, give thiamine and B vitamins before feeding, and monitor potassium, phosphate and magnesium closely.",
      },
      {
        id: "pe_nut_support",
        cluster: "Nutritional management (2 marks)",
        name: "Enteral and parenteral nutrition and their complications",
        keyFacts: "Refeeding syndrome causes hypophosphataemia, hypokalaemia and hypomagnesaemia with fluid overload, arrhythmia and, if unrecognised, death — the danger comes from feeding too fast, not from feeding at all.",
        presentation: "Enteral complications: tube misplacement (the reason for pH testing and radiographic confirmation before feeding), aspiration, diarrhoea, blockage and refeeding syndrome. Parenteral complications: line-related sepsis and thrombosis, metabolic derangement, hyperglycaemia, deranged liver function and cholestasis, and refeeding syndrome.",
        investigations: "Confirm nasogastric tube position with aspirate at pH 5.5 or below, and with a chest radiograph interpreted by a competent person if this cannot be obtained — misplaced nasogastric feeding is a never event. Monitor electrolytes, glucose, liver function and fluid balance during artificial feeding, daily at first.",
        treatment: "Involve the nutrition team, including dietitians, pharmacists and nutrition nurses, early. Use a dedicated lumen for parenteral nutrition with strict aseptic technique, and suspect line sepsis in any unexplained fever in a patient with a feeding line. In short bowel and high-output stoma, restrict hypotonic fluids, give oral rehydration solution, use high-dose loperamide and proton pump inhibitors, and involve intestinal failure services early.",
      },

      // ---------------- HAEMOSTASIS & BLOOD PRODUCTS (3 marks) ----------------
      {
        id: "pe_blood_components",
        cluster: "Haemostasis & blood products (3 marks)",
        name: "Blood components and their indications",
        keyFacts: "Restrictive transfusion thresholds — a haemoglobin trigger of 70 g/L, or 80 g/L in acute coronary syndrome — are as safe as or safer than liberal transfusion in most surgical patients.",
        presentation: "Components: red cells (stored up to 35 days at 4 degrees Celsius), platelets (stored at 22 degrees with agitation for 5 to 7 days, so at higher infection risk), fresh frozen plasma (all coagulation factors), cryoprecipitate (fibrinogen, factor VIII, von Willebrand factor and factor XIII) and prothrombin complex concentrate (factors II, VII, IX and X).",
        investigations: "Group and save identifies the ABO and RhD group and screens for antibodies; cross-match assigns specific units. Electronic issue is possible where there are no antibodies and identity is verified. Correct patient identification at sampling and at administration is the single most important safety step, because most fatal reactions are clerical errors.",
        treatment: "Indications: platelets above 50 times ten to the ninth per litre for most surgery and above 100 for neurosurgical or ophthalmic procedures; fresh frozen plasma for multiple factor deficiency with bleeding; cryoprecipitate or fibrinogen concentrate for fibrinogen below about 1.5 g/L in major haemorrhage. Alternatives to transfusion include preoperative iron and erythropoietin, tranexamic acid, cell salvage and meticulous surgical haemostasis.",
      },
      {
        id: "pe_blood_reactions",
        cluster: "Haemostasis & blood products (3 marks)",
        name: "Transfusion reactions and patient safety",
        keyFacts: "Acute haemolytic transfusion reaction from ABO incompatibility presents within minutes with fever, loin or chest pain, hypotension and haemoglobinuria — stop the transfusion immediately, keep the line, and inform the laboratory.",
        presentation: "Acute reactions: haemolytic, febrile non-haemolytic (common, mild), allergic and anaphylactic, transfusion-associated circulatory overload (breathlessness, hypertension, raised jugular venous pressure) and transfusion-related acute lung injury (within 6 hours, hypoxia, bilateral infiltrates, usually normotensive). Delayed reactions include delayed haemolysis, post-transfusion purpura, iron overload and transfusion-associated graft-versus-host disease.",
        investigations: "Stop or slow the transfusion depending on severity, check the identity of the patient and the unit, and inform the transfusion laboratory. Send blood for repeat group and cross-match, direct antiglobulin test, full blood count, renal function, coagulation, lactate dehydrogenase and cultures, plus a urine sample for haemoglobin.",
        treatment: "Manage haemolytic reactions with fluid resuscitation and support of renal function. Treat circulatory overload with oxygen and diuretics and, in future, transfuse slowly with diuretic cover. Transfusion-related acute lung injury is treated supportively and reported so the donor can be investigated. Report all serious events to the Serious Hazards of Transfusion scheme. Irradiated components are used for the severely immunosuppressed and after certain treatments, to prevent graft-versus-host disease.",
      },
      {
        id: "pe_blood_massive",
        cluster: "Haemostasis & blood products (3 marks)",
        name: "Major haemorrhage and its management",
        keyFacts: "The lethal triad is hypothermia, acidosis and coagulopathy, each worsening the others — which is why damage control surgery aims to stop bleeding and contamination quickly and then correct physiology in intensive care before definitive repair.",
        presentation: "Major haemorrhage is defined pragmatically as the loss of one blood volume in 24 hours, half a blood volume in 4 hours, or ongoing loss exceeding 150 mL per minute. Recognise it early: the young compensate until they suddenly do not.",
        investigations: "Serial full blood count, coagulation, fibrinogen, calcium, blood gases and lactate. Viscoelastic testing with thromboelastography or rotational thromboelastometry allows targeted component therapy. Remember that haemoglobin is normal early in acute haemorrhage because there has been no time for dilution.",
        treatment: "Activate the major haemorrhage protocol, which delivers packs of red cells, plasma and platelets in a defined ratio, and appoint a single person to communicate with the laboratory. Give tranexamic acid within 3 hours in trauma. Keep the patient warm, correct ionised calcium (citrate binds it), and avoid excessive crystalloid. The definitive treatment of bleeding is to stop the bleeding — surgery or interventional radiology — and this must not be delayed by resuscitation.",
      },

      // ---------------- COAGULATION, DVT & EMBOLISM (3 marks) ----------------
      {
        id: "pe_coag_risk",
        cluster: "Coagulation, DVT & embolism (3 marks)",
        name: "Thrombosis risk, prophylaxis and Virchow's triad",
        keyFacts: "Virchow's triad — endothelial injury, stasis and hypercoagulability — is satisfied by almost every surgical patient, which is why risk assessment and prophylaxis are mandatory rather than discretionary.",
        presentation: "Risk factors: surgery itself (especially major abdominal, pelvic, orthopaedic and cancer surgery), immobility, malignancy, previous venous thromboembolism, thrombophilia, obesity, pregnancy and the puerperium, oestrogen therapy, dehydration and age.",
        investigations: "Every patient is risk-assessed on admission and reassessed at 24 hours or when the clinical picture changes. Thrombophilia testing is not routine and is considered for unprovoked events in the young, recurrent events or a strong family history; it should not be performed during an acute event or while on anticoagulation.",
        treatment: "Mechanical prophylaxis with antiembolism stockings (contraindicated in peripheral arterial disease, and to be avoided in severe leg oedema and dermatitis) and intermittent pneumatic compression. Pharmacological prophylaxis with low molecular weight heparin, dose-adjusted for renal function and weight. Extended prophylaxis for 28 days after major abdominal or pelvic cancer surgery and 35 days after hip arthroplasty. Timing around neuraxial blocks must respect defined intervals.",
      },
      {
        id: "pe_coag_diagnosis",
        cluster: "Coagulation, DVT & embolism (3 marks)",
        name: "Diagnosis and treatment of venous thromboembolism",
        keyFacts: "D-dimer has essentially no diagnostic value in the postoperative patient because surgery raises it — use imaging directly when clinical suspicion is significant.",
        presentation: "Deep vein thrombosis: unilateral calf or thigh swelling, tenderness, warmth and dilated superficial veins. Pulmonary embolism: breathlessness, pleuritic pain, haemoptysis, tachycardia and hypoxia; in the postoperative patient it may present as unexplained tachycardia, hypoxia or collapse.",
        investigations: "Wells score guides the pathway. Proximal leg vein ultrasound for deep vein thrombosis, repeated at a week if initially negative in a high-probability patient. Computed tomography pulmonary angiography for pulmonary embolism, with ventilation-perfusion scanning in renal impairment or pregnancy. Echocardiography to assess right ventricular strain in the unstable patient.",
        treatment: "Anticoagulation with a direct oral anticoagulant or low molecular weight heparin, balancing recent surgery and bleeding risk. Duration is at least three months, longer for unprovoked or cancer-associated events. Massive pulmonary embolism with haemodynamic compromise is treated with thrombolysis, or with catheter-directed therapy or embolectomy when thrombolysis is contraindicated by recent surgery. An inferior vena cava filter is considered when anticoagulation is absolutely contraindicated, and should be retrieved when it is no longer needed.",
      },
      {
        id: "pe_coag_anticoag",
        cluster: "Coagulation, DVT & embolism (3 marks)",
        name: "Perioperative anticoagulation and reversal",
        keyFacts: "Warfarin reversal for major bleeding is vitamin K plus prothrombin complex concentrate, which works within minutes; fresh frozen plasma is slower, requires large volumes and is second-line.",
        presentation: "Perioperative planning balances the risk of thrombosis if anticoagulation is stopped against the risk of bleeding if it is continued. High thrombotic risk includes mechanical mitral valves, recent venous thromboembolism within three months, high CHA2DS2-VASc scores and recent stroke.",
        investigations: "Warfarin is monitored by international normalised ratio and generally stopped 5 days before major surgery, with the international normalised ratio checked on the day before. Direct oral anticoagulants are stopped based on renal function and procedural bleeding risk, typically 24 to 72 hours, and do not require bridging. Check platelet count and renal function before restarting.",
        treatment: "Bridging with therapeutic low molecular weight heparin is reserved for the highest thrombotic risk because it increases bleeding without clear benefit in most patients. Reversal agents: protamine for unfractionated heparin (partial for low molecular weight heparin), vitamin K and prothrombin complex concentrate for warfarin, idarucizumab for dabigatran and andexanet alfa for factor Xa inhibitors where available. Restart anticoagulation when haemostasis is secure, usually 24 to 72 hours postoperatively, and document the plan clearly on discharge.",
      },

      // ---------------- METABOLIC & ENDOCRINE (5 marks) ----------------
      {
        id: "pe_met_thyroid",
        cluster: "Metabolic & endocrine disorders (5 marks)",
        name: "Perioperative thyroid disease",
        keyFacts: "Elective surgery should be performed on a euthyroid patient; operating on an inadequately controlled thyrotoxic patient risks thyroid storm, which has a high mortality.",
        presentation: "Hyperthyroidism causes tachyarrhythmia, heart failure, weight loss, heat intolerance and, in Graves disease, eye signs. Hypothyroidism causes bradycardia, reduced cardiac output, delayed drug metabolism, hypothermia, ileus and, at the extreme, myxoedema coma with hypoventilation and hyponatraemia.",
        investigations: "Thyroid function tests before elective surgery in anyone with symptoms or known disease. Avoid testing routinely in the acutely unwell, where sick euthyroid syndrome is common and misleading. Assess airway and tracheal deviation in goitre, and vocal cords before and after thyroid surgery.",
        treatment: "Thyroid storm: propranolol (which also blocks peripheral conversion), propylthiouracil or carbimazole, iodine given at least an hour after the antithyroid drug, corticosteroids, active cooling and treatment of the precipitant. Myxoedema coma: intravenous thyroid hormone with corticosteroids (because coexisting adrenal insufficiency must be covered), warming and ventilatory support. Continue thyroid replacement through the perioperative period.",
      },
      {
        id: "pe_met_calcium",
        cluster: "Metabolic & endocrine disorders (5 marks)",
        name: "Perioperative calcium disorders",
        keyFacts: "Hypocalcaemia after total thyroidectomy reflects parathyroid devascularisation; perioral tingling, Chvostek sign and Trousseau sign with a prolonged QT interval are the clinical features, and calcium is checked routinely postoperatively.",
        presentation: "Hypercalcaemia: bones, stones, abdominal moans and psychic groans, with dehydration, arrhythmia and confusion when severe. Hypocalcaemia: paraesthesia, muscle cramps, carpopedal spasm, laryngospasm, seizures and prolonged QT interval.",
        investigations: "Always correct calcium for albumin, or measure ionised calcium. Check magnesium, because hypomagnesaemia causes refractory hypocalcaemia. In hypercalcaemia, measure parathyroid hormone to distinguish primary hyperparathyroidism from malignancy. After thyroid or parathyroid surgery, measure calcium and, in some units, parathyroid hormone at defined intervals.",
        treatment: "Severe hypercalcaemia: aggressive intravenous 0.9 per cent sodium chloride rehydration first, then bisphosphonates, with treatment of the cause; loop diuretics are used only once the patient is volume-replete and are not first-line. Symptomatic hypocalcaemia: intravenous calcium gluconate with cardiac monitoring, then oral calcium and alfacalcidol. Hungry bone syndrome after parathyroidectomy causes profound and prolonged hypocalcaemia requiring substantial replacement.",
      },
      {
        id: "pe_met_steroid",
        cluster: "Metabolic & endocrine disorders (5 marks)",
        name: "Corticosteroid therapy and adrenal insufficiency",
        keyFacts: "A patient taking more than the equivalent of 5 mg prednisolone daily for more than three months should be assumed to have a suppressed hypothalamic-pituitary-adrenal axis and given perioperative steroid cover.",
        presentation: "Complications of long-term corticosteroids: adrenal suppression, diabetes, hypertension, osteoporosis, thin skin and poor wound healing, immunosuppression and masking of infection, cataracts, proximal myopathy and mood disturbance. Addisonian crisis presents with hypotension unresponsive to fluids, hyponatraemia, hyperkalaemia, hypoglycaemia and abdominal pain.",
        investigations: "Short synacthen test assesses adrenal reserve where the diagnosis is uncertain, but treatment must not wait for it in a crisis. Check sodium, potassium, glucose and cortisol before giving hydrocortisone if possible, but never delay treatment. Review the steroid history including inhaled and topical preparations, which can also suppress the axis.",
        treatment: "Perioperative cover: continue the usual dose and add hydrocortisone according to the magnitude of surgery, with more and longer cover for major procedures. Addisonian crisis: immediate intravenous hydrocortisone 100 mg and fluid resuscitation with 0.9 per cent sodium chloride, glucose for hypoglycaemia and treatment of the precipitant. Never stop long-term steroids abruptly, and ensure patients have a steroid alert card and sick-day rules.",
      },
      {
        id: "pe_met_sodium",
        cluster: "Metabolic & endocrine disorders (5 marks)",
        name: "Sodium disorders in the surgical patient",
        keyFacts: "Correct chronic hyponatraemia by no more than 8 to 10 mmol/L in 24 hours; faster correction risks osmotic demyelination, which is irreversible.",
        presentation: "Postoperative hyponatraemia is common and usually dilutional, from raised antidiuretic hormone (pain, nausea, opioids, surgery itself) combined with hypotonic fluid. Symptoms progress from nausea and headache to confusion, seizures and coma. Hypernatraemia usually reflects water deficit from inadequate intake, gastrointestinal or renal losses, or excessive sodium administration.",
        investigations: "Assess volume status clinically, then measure plasma and urine osmolality and urine sodium. Syndrome of inappropriate antidiuretic hormone secretion: hyponatraemia, low plasma osmolality, urine osmolality above 100 mOsm/kg, urine sodium above 30 mmol/L, clinical euvolaemia and normal thyroid and adrenal function. Exclude hypothyroidism and adrenal insufficiency before making the diagnosis.",
        treatment: "Stop hypotonic fluids and treat the cause. Hypovolaemic hyponatraemia is corrected with 0.9 per cent sodium chloride; syndrome of inappropriate antidiuretic hormone secretion is treated with fluid restriction. Severe symptomatic hyponatraemia with seizures requires hypertonic saline under close supervision with strict limits on the rate of rise. Hypernatraemia is corrected slowly with enteral water or hypotonic fluid, again avoiding rapid shifts.",
      },
      {
        id: "pe_met_potassium",
        cluster: "Metabolic & endocrine disorders (5 marks)",
        name: "Potassium disorders and other electrolyte emergencies",
        keyFacts: "Hyperkalaemia with electrocardiographic changes or a potassium above 6.5 mmol/L is treated first with calcium gluconate to stabilise the myocardium — calcium does not lower potassium, it buys time.",
        presentation: "Hyperkalaemia: often asymptomatic until arrhythmia, with electrocardiographic progression from tall tented T waves through a small or absent P wave and widened QRS to a sine wave and cardiac arrest. Causes include acute kidney injury, potassium-sparing drugs, angiotensin-converting enzyme inhibitors, tissue breakdown from crush injury or rhabdomyolysis, acidosis, suxamethonium and blood transfusion.",
        investigations: "Confirm the result and exclude a haemolysed sample, but treat first when the electrocardiogram is abnormal. Check renal function, acid-base status, creatine kinase, calcium and magnesium, and review the drug chart. Hypokalaemia causes weakness, ileus, arrhythmia, U waves and a prolonged QT interval, and is exacerbated by hypomagnesaemia.",
        treatment: "Hyperkalaemia: 10 mL of 10 per cent calcium gluconate, then insulin with dextrose and nebulised salbutamol to shift potassium intracellularly, then removal by treating the cause, a potassium binder or dialysis. Hypokalaemia: replace potassium and always check and replace magnesium, because potassium cannot be corrected while magnesium is low. Peripheral potassium infusion rates are limited; higher rates require central access and cardiac monitoring.",
      },
    ],
  },

  {
    id: "skills",
    name: "Basic Surgical Skills & Safe Surgery",
    short: "Surgical skills",
    icon: "🔪",
    paper: "both",
    marks: 0,
    itemNoun: "topics",
    fieldLabels: ["🔪 Principle", "🧵 Technique & materials", "⚠️ Safety & pitfalls"],
    blurb: "Module 3 of the syllabus. It carries no dedicated marks in the Part A blueprint, but the underlying knowledge — wound healing, sutures, diathermy, drains, anastomosis — appears throughout Paper 2 and dominates the Part B OSCE. Worth keeping green.",
    conditions: [
      {
        id: "sk_asepsis",
        cluster: "Preparation for surgery",
        name: "Preparation of the surgeon and the patient",
        keyFacts: "Alcoholic chlorhexidine is generally superior to povidone-iodine for skin preparation, but it must be allowed to dry fully before diathermy is used, and must not pool beneath the patient.",
        presentation: "Surgeon preparation: bare below the elbows, nails short and clean, no jewellery, an initial surgical scrub with a brush used only for the nails, drying with sterile towels without contaminating the hands, then gowning and closed gloving to maintain surface sterility. Alcohol rub is used between consecutive clean cases.",
        investigations: "Patient preparation: confirm identity, site marking and consent; check allergies including to chlorhexidine, iodine and latex; remove hair with clippers only if necessary and never with a razor; prepare the skin from the incision outwards; and drape to create and maintain a sterile field.",
        treatment: "Protect mucosa, cornea and open neural tissue from alcoholic preparation. Maintain the sterile field throughout: anything below waist level or behind the surgeon is unsterile, and the field must be reassessed after any breach. Double gloving reduces the consequences of perforation and is recommended for high-risk procedures.",
      },
      {
        id: "sk_local",
        cluster: "Local anaesthesia",
        name: "Safe administration of local anaesthesia",
        keyFacts: "Maximum doses: lidocaine 3 mg/kg plain and 7 mg/kg with adrenaline; bupivacaine 2 mg/kg. A 1 per cent solution contains 10 mg per mL, so 20 mL of 1 per cent lidocaine is 200 mg.",
        presentation: "Choose the agent by onset and duration: lidocaine has rapid onset and moderate duration; bupivacaine is slower in onset with a long duration and is more cardiotoxic. Adrenaline prolongs the block, reduces bleeding and allows a higher maximum dose.",
        investigations: "Always calculate the maximum dose for the individual patient before starting. Aspirate before injecting to avoid intravascular injection, inject slowly, and maintain verbal contact with the patient so early toxicity is detected. Local anaesthetic works poorly in infected acidic tissue because the drug is ionised.",
        treatment: "Local anaesthetic systemic toxicity progresses from perioral tingling, tinnitus and a metallic taste to confusion, seizures and cardiovascular collapse. Management is to stop injecting, call for help, secure the airway, give oxygen, treat seizures and give intravenous lipid emulsion, with prolonged resuscitation if arrest occurs. Know where the lipid emulsion is kept in your theatre.",
      },
      {
        id: "sk_wounds",
        cluster: "Wounds & closure",
        name: "Surgical wounds, incisions and closure",
        keyFacts: "Langer's lines are the natural lines of skin tension; incisions placed parallel to them heal with finer, stronger and more cosmetic scars.",
        presentation: "Wound classification by contamination: clean, clean-contaminated, contaminated and dirty, with rising infection rates. Healing by primary intention (direct apposition), secondary intention (granulation and contraction) or tertiary or delayed primary closure (observation then closure).",
        investigations: "Plan an incision for access, extensibility, vascularity, function and cosmesis. Consider the underlying anatomy, the segmental nerve supply of the abdominal wall, and the need for future access. Handle tissues gently: crushed, dried or devascularised tissue heals badly and becomes infected.",
        treatment: "Closure principles: accurate, tension-free apposition of like to like, obliteration of dead space, and appropriate suture choice. Mass closure of the abdominal wall uses a continuous slowly absorbable suture with a suture-length to wound-length ratio of at least 4 to 1, using small bites, which reduces incisional hernia. Skin sutures are removed at 5 days on the face, 7 to 10 on the trunk and 10 to 14 on the limbs and back.",
      },
      {
        id: "sk_sutures",
        cluster: "Wounds & closure",
        name: "Sutures, needles and knots",
        keyFacts: "Suture gauge: the more zeros, the finer the suture — so 5-0 is much finer than 1. Absorbable sutures are used where support is temporary; non-absorbable where it must be permanent.",
        presentation: "Absorbable: catgut (obsolete in the United Kingdom), polyglactin (Vicryl, about 60 days), poliglecaprone (Monocryl, about 90 to 120 days), polydioxanone (PDS, about 180 days). Non-absorbable: silk (braided, handles well, high tissue reactivity), nylon, polypropylene (Prolene, inert, slippery, used for vascular work) and steel.",
        investigations: "Monofilament sutures have low tissue drag and a low infection risk but poorer handling and knot security; braided sutures handle and knot better but harbour bacteria. Needles: cutting for skin and tough tissue, round-bodied (taper point) for bowel and vessels, blunt for fascia to reduce needlestick injury.",
        treatment: "Knot security requires enough throws for the material — more for monofilament and polypropylene — laid square and flat without excessive tension. Techniques include one-handed, two-handed and instrument tying, and superficial and deep tying. Avoid tying too tight: strangulated tissue necroses and the wound fails.",
      },
      {
        id: "sk_haemostasis",
        cluster: "Operative technique",
        name: "Haemostasis and the safe use of diathermy",
        keyFacts: "Bipolar diathermy confines current to the tissue between the forceps tips, making it safe on appendages and near nerves; monopolar current travels through the patient to the return electrode.",
        presentation: "Methods of haemostasis: direct pressure, ligation with tie or suture, transfixion suture for a pedicle, clips, diathermy, energy devices such as ultrasonic and advanced bipolar, topical haemostatic agents, and packing for damage control.",
        investigations: "Anticipate bleeding: know the vessels in the field, control the pedicle before dividing, and have suction, swabs and an assistant ready. Persistent oozing despite technical control should prompt consideration of coagulopathy, hypothermia, acidosis, antiplatelet or anticoagulant drugs and undiagnosed bleeding disorders.",
        treatment: "Diathermy hazards: return plate burns, alternative site burns via other earthed contacts, channelling injury in narrow pedicles, interference with cardiac devices, surgical smoke and fire risk with alcoholic preparation and oxygen. Check the plate, avoid activating near metal implants where possible, use the lowest effective setting and never activate the pencil while it is not in the field.",
      },
      {
        id: "sk_drains_biopsy",
        cluster: "Operative technique",
        name: "Drains, biopsy technique and specimen handling",
        keyFacts: "Drains do not prevent complications and do not compensate for imperfect surgery; used indiscriminately they cause infection, pain and delayed recovery, which is why enhanced recovery protocols avoid them.",
        presentation: "Drains may be open or closed, active (suction) or passive (gravity). Legitimate indications: to obliterate dead space, to drain an established collection, to detect a leak where one would change management, and after certain specific procedures. They should be removed as soon as their purpose is served.",
        investigations: "Biopsy techniques: excisional (whole lesion, needed for suspected melanoma and lymph nodes for lymphoma), incisional, core needle (preserves architecture, gives receptor status) and fine-needle aspiration (cytology only). Choose the technique by what the pathologist needs to answer the clinical question.",
        treatment: "Label every specimen correctly at the time of removal, with the patient's identifiers, the site and any orientation marks, and complete the request form with the clinical question — mislabelled specimens are a serious incident. Send lymph nodes for suspected lymphoma fresh, not in formalin. Confirm specimen labelling during the sign-out phase of the surgical checklist.",
      },
      {
        id: "sk_anastomosis",
        cluster: "Operative technique",
        name: "Principles of anastomosis and skin cover",
        keyFacts: "The four requirements of a safe anastomosis are good blood supply, no tension, accurate apposition of healthy tissue, and the absence of distal obstruction or sepsis.",
        presentation: "Anastomoses may be hand-sewn or stapled, end-to-end, end-to-side or side-to-side, in one or two layers, interrupted or continuous. Outcomes depend far more on the general principles and on patient factors than on the specific technique chosen.",
        investigations: "Factors that increase leak risk: poor perfusion, tension, malnutrition, steroids, immunosuppression, diabetes, smoking, radiotherapy, contamination, emergency surgery, low rectal anastomosis and inadequate surgical experience. When conditions are unfavourable, a stoma or delayed anastomosis is the safer decision.",
        treatment: "The reconstructive ladder for skin cover runs from healing by secondary intention, through direct closure, split-thickness graft, full-thickness graft, local flap, regional flap and free tissue transfer. Grafts require a well-vascularised, non-infected bed and take by imbibition, inosculation and revascularisation; they will not take on bare bone, cartilage or tendon without periosteum, perichondrium or paratenon. Flaps bring their own blood supply and can cover such defects.",
      },
      {
        id: "sk_procedures",
        cluster: "Core practical procedures",
        name: "Airway, chest drain, vascular access and catheterisation",
        keyFacts: "A chest drain is inserted in the safe triangle — bordered by the lateral border of pectoralis major, the anterior border of latissimus dorsi and a horizontal line at the nipple level — passing over the top of the rib below to avoid the neurovascular bundle.",
        presentation: "Core procedures every core surgical trainee must be able to perform: basic airway management, central and peripheral venous access, chest drain insertion, urethral catheterisation and surgical drainage of pus. Surgical airway (cricothyroidotomy) is required in the can't intubate, can't oxygenate scenario.",
        investigations: "Consent where possible, use aseptic technique, use ultrasound guidance for central venous access, and confirm position afterwards — chest radiograph after a central line or chest drain, and documentation of urine drainage and residual volume after catheterisation. Check coagulation and platelets before invasive procedures where relevant.",
        treatment: "Complications to know and avoid: pneumothorax and arterial puncture with central access; lung, liver, spleen and cardiac injury with chest drains; urethral trauma and false passage with catheterisation, and never force a catheter in suspected urethral injury. Blood at the meatus, a high-riding prostate or perineal bruising after trauma mandates a retrograde urethrogram before catheterisation. Always document the indication, the technique, the findings and the aftercare plan.",
      },
    ],
  },
];
