// ===================================================================
// MRCS PART A — Paper 2, Sections 3-5
//   trauma (30) · surgical care of children (7) · medico-legal (3)
//
// The professional practice section also carries Module 8 (management of the
// dying patient), Module 9 (organ and tissue transplantation) and Module 10
// (professional behaviour and leadership skills), which the blueprint folds
// into the three medico-legal marks.
// ===================================================================

window.MRCS_TRAUMA = [
  {
    id: "trauma",
    name: "Trauma & the Multiply Injured Patient",
    short: "Trauma",
    icon: "🚑",
    paper: "paper2",
    marks: 30,
    itemNoun: "topics",
    fieldLabels: ["🚑 Assessment", "🔬 Investigations", "💊 Management"],
    blurb: "Thirty marks, and the most systematised part of the whole syllabus — it follows the Advanced Trauma Life Support structure almost exactly. Organ-specific trauma is ten marks and fractures and dislocations another eight, so those two clusters alone are worth more than microbiology, imaging and statistics combined.",
    conditions: [

      // ---------------- GENERAL (4 marks) ----------------
      {
        id: "tr_gen_primary",
        cluster: "General principles (4 marks)",
        name: "Primary survey and the ATLS approach",
        keyFacts: "Treat the greatest threat to life first, and do not wait for a definitive diagnosis before treating. The sequence is catastrophic haemorrhage, then airway with cervical spine control, breathing, circulation, disability and exposure.",
        presentation: "Airway: talk to the patient — a normal voice largely clears the airway. Look for obstruction, stridor, facial or laryngeal injury, and maintain manual in-line stabilisation of the cervical spine. Breathing: respiratory rate, chest movement, percussion, auscultation, tracheal position, oxygen saturation. Circulation: pulse, blood pressure, capillary refill, external haemorrhage control, and the five places blood hides — chest, abdomen, pelvis, long bones and the floor.",
        investigations: "Adjuncts to the primary survey: electrocardiographic monitoring, pulse oximetry, capnography, arterial blood gases, urinary and gastric catheters (with the caveats about urethral and base-of-skull injury), chest and pelvic radiographs, and focused assessment with sonography for trauma. Whole-body computed tomography is used in the stable patient. Re-evaluate constantly; if the patient deteriorates, go back to A.",
        treatment: "Give high-flow oxygen, obtain two large-bore intravenous cannulae with blood for cross-match, and use blood products rather than large volumes of crystalloid in haemorrhagic shock. Give tranexamic acid within 3 hours. Keep the patient warm. The secondary survey is a head-to-toe examination with a full history (allergies, medications, past history, last meal, events) and is performed only once the primary survey is complete and the patient is not deteriorating.",
        management: {
          def: "A[\"Trauma call: major trauma\"]:::start --> B[\"<C> Catastrophic haemorrhage control\"]:::danger\nB --> C[\"A: airway + cervical spine control\"]:::process\nC --> D[\"B: breathing, high-flow oxygen, decompress tension pneumothorax\"]:::process\nD --> E[\"C: circulation, 2 large cannulae, blood products, TXA\"]:::process\nE --> F{\"Haemodynamically stable?\"}:::decision\nF -- \"Yes\" --> G[\"Whole-body CT trauma scan\"]:::good\nF -- \"No\" --> H[\"FAST + chest and pelvic radiographs\"]:::warn\nH --> I{\"Source of bleeding?\"}:::decision\nI -- \"Abdomen\" --> J[\"Laparotomy\"]:::danger\nI -- \"Chest\" --> K[\"Chest drain, thoracotomy if massive\"]:::danger\nI -- \"Pelvis\" --> L[\"Binder, then packing or angioembolisation\"]:::danger\nG --> M[\"D and E, secondary survey, definitive care\"]:::process",
          tips: {
            "B": "External catastrophic haemorrhage takes priority over the airway — a tourniquet or pressure dressing comes first.",
            "C": "Manual in-line stabilisation, not traction. Talking in a normal voice largely clears the airway.",
            "E": "Tranexamic acid within 3 hours reduces mortality; after 3 hours it may cause harm.",
            "F": "The unstable patient does not go to the scanner — the scanner is not a resuscitation room.",
            "L": "Apply the pelvic binder at the level of the greater trochanters, not the iliac crests.",
          },
        },
      },
      {
        id: "tr_gen_scoring",
        cluster: "General principles (4 marks)",
        name: "Trauma scoring, triage and major incidents",
        keyFacts: "The Injury Severity Score squares the highest Abbreviated Injury Scale score in each of the three most severely injured body regions and sums them; a score above 15 defines major trauma.",
        presentation: "Scoring systems are anatomical (Abbreviated Injury Scale, Injury Severity Score), physiological (Revised Trauma Score, Glasgow Coma Scale) or combined (TRISS). They are used for triage, audit, benchmarking and research rather than for individual clinical decisions.",
        investigations: "Triage sorts patients by clinical need and available resources. In a major incident, triage sieve is a rapid assessment of walking, airway, respiratory rate and circulation to assign priorities P1 (immediate), P2 (urgent), P3 (delayed) and expectant. The principle changes from doing the most for each individual to doing the most for the greatest number.",
        treatment: "Major incident response follows the CSCATTT framework: command and control, safety, communication, assessment, triage, treatment and transport. Trauma networks direct patients to major trauma centres, bypassing local units where appropriate, because outcomes are better in high-volume centres. Every trauma death should be reviewed, and preventable deaths audited through the trauma audit and research network.",
      },
      {
        id: "tr_gen_children",
        cluster: "General principles (4 marks)",
        name: "Differences in the injured child and the elderly",
        keyFacts: "Children compensate for hypovolaemia extremely well and then decompensate suddenly; hypotension in an injured child indicates loss of more than 30 to 45 per cent of blood volume and is a pre-terminal sign.",
        presentation: "Children have a proportionately larger head, a more anterior and superior larynx, a more compliant chest wall (so significant intrathoracic injury occurs without rib fracture), a relatively larger surface area (so they cool quickly), and a mobile mediastinum. Their organs are less protected by fat and muscle so multisystem injury is common.",
        investigations: "Weight is estimated by formula or a length-based tape, and drug and fluid doses are weight-based. Fluid resuscitation is 10 mL/kg boluses of a balanced crystalloid, moving early to blood. Radiation exposure matters more in children so imaging should be justified carefully. Always consider non-accidental injury: an inconsistent or changing history, delayed presentation, injuries inconsistent with the developmental stage, or particular fracture patterns.",
        treatment: "In the elderly, physiological reserve is reduced, beta-blockers mask tachycardia, anticoagulants worsen bleeding, and a normal blood pressure may be relative hypotension in a chronic hypertensive. Low-energy falls in the elderly cause major injury including subdural haematoma and cervical spine fracture. Frailty predicts outcome and should trigger early senior and orthogeriatric involvement.",
      },
      {
        id: "tr_gen_damage",
        cluster: "General principles (4 marks)",
        name: "Damage control surgery and resuscitation",
        keyFacts: "Damage control surgery aims to stop bleeding and contamination, not to complete the operation: control, pack, temporarily close, correct physiology in intensive care, then return for definitive surgery at 24 to 48 hours.",
        presentation: "The trigger for damage control is physiological rather than anatomical: hypothermia below about 34 degrees Celsius, acidosis with a pH below 7.2 or a rising base deficit, and coagulopathy — the lethal triad. Continuing a long definitive operation in that state kills the patient on the table.",
        investigations: "Monitor temperature, arterial blood gases, lactate, base deficit, calcium, fibrinogen and viscoelastic testing throughout. Recognise the pattern early rather than after several hours of surgery. Damage control resuscitation runs alongside: permissive hypotension in penetrating injury without head injury, early balanced blood product transfusion, minimal crystalloid, and aggressive warming.",
        treatment: "Techniques include packing of the liver and pelvis, temporary vascular shunts, stapling off bowel without anastomosis, and temporary abdominal closure with a negative pressure dressing. Abdominal compartment syndrome is a recognised sequel: rising intra-abdominal pressure causes oliguria, high airway pressures and cardiovascular compromise, and is treated by decompression. Definitive reconstruction happens once the physiology is corrected.",
      },

      // ---------------- SHOCK (2 marks) ----------------
      {
        id: "tr_shock_haem",
        cluster: "Shock (2 marks)",
        name: "Haemorrhagic shock and its recognition",
        keyFacts: "Class I up to 15 per cent loss (normal observations), class II 15 to 30 per cent (tachycardia, narrowed pulse pressure, anxiety), class III 30 to 40 per cent (hypotension, confusion, oliguria), class IV over 40 per cent (profound hypotension, negligible urine output, lethargy).",
        presentation: "The earliest signs are tachycardia, a narrowed pulse pressure from a rising diastolic pressure, delayed capillary refill, cool peripheries, an increased respiratory rate and anxiety. Hypotension is a late sign, particularly in the young, the pregnant and the athlete. Beta-blockers, pacemakers and spinal injury blunt the tachycardic response.",
        investigations: "Base deficit and lactate reflect tissue perfusion far better than blood pressure and should be trended. Haemoglobin is normal early because there has been no time for dilution, so a normal haemoglobin never excludes significant haemorrhage. Focused assessment with sonography for trauma, chest and pelvic radiographs identify the site in the unstable patient.",
        treatment: "Control the bleeding: direct pressure, tourniquet, pelvic binder, splintage of long bones, then surgery or interventional radiology. Transfuse blood products in a balanced ratio rather than crystalloid. Give tranexamic acid within 3 hours. Reassess the response as rapid, transient or none: a transient or absent response means ongoing bleeding and mandates immediate haemorrhage control.",
      },
      {
        id: "tr_shock_other",
        cluster: "Shock (2 marks)",
        name: "Non-haemorrhagic shock in trauma and ARDS",
        keyFacts: "Neurogenic shock gives hypotension with bradycardia and warm peripheries; haemorrhagic shock gives hypotension with tachycardia and cold peripheries. Assuming a trauma patient's hypotension is neurogenic before excluding bleeding is a fatal error.",
        presentation: "Obstructive shock in trauma: tension pneumothorax (respiratory distress, tracheal deviation, absent breath sounds, hyper-resonance, distended neck veins) and cardiac tamponade (Beck's triad of hypotension, raised jugular venous pressure and muffled heart sounds, with pulsus paradoxus). Cardiogenic shock may follow blunt cardiac injury or a precipitating myocardial infarction.",
        investigations: "Tension pneumothorax is a clinical diagnosis and must not await a radiograph. Extended focused assessment with sonography for trauma identifies pericardial fluid, pneumothorax and free intraperitoneal fluid. Neurogenic shock is diagnosed only after haemorrhage has been excluded, and requires a documented level of spinal injury.",
        treatment: "Tension pneumothorax: immediate decompression, now recommended in the fourth or fifth intercostal space in the midaxillary line in adults, followed by a chest drain. Tamponade: pericardiocentesis or, better, thoracotomy in the appropriate setting. Neurogenic shock: vasopressors and often an anticholinergic, since fluids alone will not restore tone. Acute respiratory distress syndrome follows major trauma, massive transfusion, pulmonary contusion and sepsis, and is managed with lung-protective ventilation.",
      },

      // ---------------- WOUNDS & SOFT TISSUE (4 marks) ----------------
      {
        id: "tr_wound_types",
        cluster: "Wounds & soft tissue injuries (4 marks)",
        name: "Wound types, ballistic injury and bites",
        keyFacts: "High-energy projectiles cause cavitation, so the tissue damage extends far beyond the visible track; the entry wound may be small and the deep injury massive.",
        presentation: "Stab wounds cause damage along the track and are relatively predictable. Gunshot wounds vary with energy: low-velocity handgun wounds cause a permanent track, whereas high-velocity rifle and military rounds create a temporary cavity with widespread devitalisation. Blast injury has primary (pressure wave affecting gas-containing organs: lung, bowel, tympanic membrane), secondary (fragments), tertiary (displacement) and quaternary (burns, inhalation) mechanisms.",
        investigations: "Do not probe wounds blindly in the emergency department. Imaging with radiographs and computed tomography maps the track and retained fragments. Assess neurovascular status distal to any wound and examine the whole patient — projectiles do not travel in straight lines and there may be multiple wounds.",
        treatment: "Principles of wound management: control haemorrhage, assess neurovascular and tendon injury, thorough irrigation, debridement of devitalised tissue, removal of foreign material, tetanus prophylaxis and, where indicated, antibiotics. Human and animal bites are heavily contaminated (Pasteurella multocida in cats and dogs, Eikenella corrodens in humans) and are generally left open with co-amoxiclav; a clenched fist injury over the metacarpophalangeal joint requires exploration because of joint involvement. Consider rabies and blood-borne virus risk in human bites.",
      },
      {
        id: "tr_wound_softtissue",
        cluster: "Wounds & soft tissue injuries (4 marks)",
        name: "Soft tissue injury, degloving and crush injury",
        keyFacts: "Crush injury causes rhabdomyolysis with hyperkalaemia, myoglobinuric acute kidney injury and metabolic acidosis, and the potassium surge on release of the crushing force can be fatal — anticipate it before extrication.",
        presentation: "Closed degloving separates skin and subcutaneous tissue from the underlying fascia and may not be apparent on the surface, presenting later with skin necrosis. Open degloving is obvious but the viability of the flap is often overestimated. Assess soft tissue injury as carefully as the fracture in any open injury.",
        investigations: "Creatine kinase, potassium, renal function, calcium, urate and urinalysis for myoglobin in crush injury. Compartment pressures where clinical assessment is impossible. Magnetic resonance imaging or computed tomography angiography where vascular or deep soft tissue injury is suspected.",
        treatment: "Crush syndrome is treated with aggressive intravenous fluid resuscitation started before extrication where possible, management of hyperkalaemia, and monitoring for compartment syndrome and acute kidney injury. Degloved skin that is non-viable should be debrided and can sometimes be defatted and reapplied as a graft. Open injuries need early antibiotics, tetanus cover, photography, a saline-soaked dressing and combined orthoplastic management.",
      },
      {
        id: "tr_wound_compartment",
        cluster: "Wounds & soft tissue injuries (4 marks)",
        name: "Compartment syndrome",
        keyFacts: "Pain out of proportion to the injury and pain on passive stretch are the earliest reliable signs. Pulses are usually present — pulselessness is a late and pre-terminal sign for the limb.",
        presentation: "Occurs when pressure within a closed fascial compartment exceeds perfusion pressure. Causes: fractures (especially tibial and forearm), crush injury, reperfusion after ischaemia, burns, tight casts or dressings, prolonged limb positioning and extravasation. The leg has four compartments and the forearm three.",
        investigations: "Diagnosis is clinical wherever the patient can report symptoms. Compartment pressure measurement is used in the obtunded, the child and those with regional blocks: a delta pressure (diastolic minus compartment pressure) below 30 mmHg supports the diagnosis. Creatine kinase and renal function assess rhabdomyolysis.",
        treatment: "Remove all constricting dressings and casts down to skin, keep the limb at heart level rather than elevated, give oxygen and analgesia, and proceed to urgent fasciotomy of all compartments with wounds left open for delayed closure or grafting. Beware that regional anaesthesia and patient-controlled analgesia mask the cardinal symptom. Untreated, the result is Volkmann's ischaemic contracture, limb loss or death from rhabdomyolysis.",
      },
      {
        id: "tr_wound_tetanus",
        cluster: "Wounds & soft tissue injuries (4 marks)",
        name: "Wound infection prophylaxis and tetanus",
        keyFacts: "Tetanus-prone wounds include those with significant devitalised tissue, puncture wounds, contamination with soil or manure, wounds containing foreign bodies, compound fractures, and any wound presenting after more than six hours.",
        presentation: "Clostridium tetani is a spore-forming anaerobe producing tetanospasmin, which blocks inhibitory neurotransmission causing muscle spasm, trismus, risus sardonicus and opisthotonos. Gas gangrene from Clostridium perfringens causes myonecrosis with crepitus, a sweet odour and profound toxaemia.",
        investigations: "Assess immunisation status in every wound. A full course is five doses in the United Kingdom. Assessment is clinical for tetanus and gas gangrene; do not wait for microbiology. Radiographs may show gas in the tissues in clostridial infection.",
        treatment: "Thorough wound toilet and debridement is the most important measure. Give a tetanus booster if immunisation is incomplete or uncertain, and tetanus immunoglobulin as well for high-risk wounds in the inadequately immunised. Gas gangrene requires immediate radical debridement or amputation, high-dose benzylpenicillin with clindamycin, and critical care support. Antibiotic prophylaxis for contaminated wounds does not substitute for surgical debridement.",
      },

      // ---------------- BURNS (2 marks) ----------------
      {
        id: "tr_burn_assessment",
        cluster: "Burns (2 marks)",
        name: "Burn assessment, depth and area",
        keyFacts: "Estimate area with the rule of nines in adults (head 9, each arm 9, each leg 18, front torso 18, back torso 18, perineum 1) or the patient's own palm including fingers as approximately 1 per cent. Simple erythema is not included.",
        presentation: "Superficial: erythema only, painful, blanching, no blistering, heals in about a week. Superficial partial thickness: blisters, extremely painful, brisk capillary refill, heals in two to three weeks. Deep partial thickness: mottled red and white, less sensate, sluggish refill, heals slowly with scarring. Full thickness: white, brown or leathery, painless, non-blanching, requires grafting.",
        investigations: "Assess for inhalational injury in every burn from an enclosed space: facial burns, singed nasal hairs, soot in the mouth or sputum, hoarseness, stridor and a reduced conscious level. Measure carboxyhaemoglobin, remembering that pulse oximetry reads falsely normal in carbon monoxide poisoning. Look for circumferential burns of the limbs, chest and neck that will need escharotomy.",
        treatment: "First aid: stop the burning process, cool with running water for 20 minutes (effective up to 3 hours), remove jewellery and constricting items, and cover with cling film — while actively avoiding hypothermia. Chemical burns need copious irrigation, with specific treatments for hydrofluoric acid (calcium gluconate gel). Electrical injury requires cardiac monitoring and assessment for deep tissue damage that is far greater than the surface suggests.",
      },
      {
        id: "tr_burn_management",
        cluster: "Burns (2 marks)",
        name: "Burn resuscitation and definitive care",
        keyFacts: "The Parkland formula gives 4 mL times body weight in kilograms times percentage total body surface area burned of crystalloid over 24 hours, with half in the first 8 hours calculated from the time of the burn, not the time of arrival.",
        presentation: "Fluid resuscitation is generally indicated for burns over 15 per cent in adults and 10 per cent in children. Titrate to urine output — 0.5 mL/kg/h in adults and 1 mL/kg/h in children — rather than adhering rigidly to the formula, since both under- and over-resuscitation cause harm.",
        investigations: "Referral criteria to a burns service include burns over 10 per cent in adults or 5 per cent in children, all full-thickness burns, burns to the face, hands, feet, perineum or over joints, circumferential burns, electrical and chemical burns, inhalational injury, and burns in the very young, the elderly or those with significant comorbidity. Non-accidental injury must be considered in children.",
        treatment: "Early intubation if inhalational injury is suspected, before oedema makes it impossible. Escharotomy for circumferential full-thickness burns compromising perfusion or ventilation. Analgesia is often underestimated and must be generous. Burns are hypermetabolic, so early enteral nutrition is essential. Definitive management is debridement and split-thickness skin grafting for deep burns, with attention to scar management, splinting and rehabilitation.",
      },

      // ---------------- FRACTURES & DISLOCATIONS (8 marks) ----------------
      {
        id: "tr_fr_principles",
        cluster: "Fractures & dislocations (8 marks)",
        name: "Fracture classification and pathophysiology",
        keyFacts: "Describe every fracture systematically: bone, site, open or closed, pattern, displacement, angulation, rotation, shortening, articular involvement, and the neurovascular and soft tissue status.",
        presentation: "Patterns and their mechanisms: transverse (direct or bending), oblique and spiral (rotational), comminuted (high energy), segmental, avulsion (tendon or ligament traction), greenstick and buckle (children), and pathological (through abnormal bone). Stress fractures follow repetitive loading.",
        investigations: "Two orthogonal radiographic views including the joints above and below, as a minimum. Computed tomography for intra-articular and complex fractures; magnetic resonance imaging for occult hip and scaphoid fractures and for soft tissue injury. Salter-Harris classification for physeal injuries in children predicts growth disturbance. Gustilo-Anderson classification grades open fractures.",
        treatment: "Bone healing is primary (direct, without callus, with absolute stability and compression) or secondary (with callus, under relative stability). Principles of management are reduce, hold and rehabilitate, with the choice of cast, traction, external fixation or internal fixation determined by the fracture, the soft tissues and the patient. Early mobilisation of the patient and the uninjured joints prevents stiffness and thromboembolism.",
      },
      {
        id: "tr_fr_open",
        cluster: "Fractures & dislocations (8 marks)",
        name: "Open fractures and orthoplastic management",
        keyFacts: "Open fractures need intravenous antibiotics within one hour of injury, tetanus cover, photography, a saline-soaked dressing under an occlusive layer, splintage, and a planned combined orthopaedic and plastic surgical procedure — not repeated bedside washouts.",
        presentation: "Gustilo-Anderson classification: type I wound under 1 cm with minimal contamination; type II wound 1 to 10 cm with moderate soft tissue damage; type III extensive soft tissue damage, subdivided into IIIA with adequate cover, IIIB requiring flap cover and IIIC with arterial injury requiring repair.",
        investigations: "Assess and document neurovascular status before and after any manipulation. Radiographs of the affected bone and the joints above and below. Computed tomography angiography where vascular injury is suspected, but do not delay revascularisation in a limb with hard signs of arterial injury.",
        treatment: "Debridement should be performed by a senior orthopaedic and plastic surgeon together, on a planned list, ideally within 12 to 24 hours, and definitive skeletal stabilisation with soft tissue cover achieved within 72 hours. Vascular injury requires immediate repair or shunting, with fasciotomy considered. Avoid the historically taught six-hour rule as an absolute; the quality of debridement matters more than the timing within that window.",
      },
      {
        id: "tr_fr_upperlimb",
        cluster: "Fractures & dislocations (8 marks)",
        name: "Upper limb fractures and dislocations",
        keyFacts: "A supracondylar fracture of the humerus in a child threatens the brachial artery and the anterior interosseous nerve — the inability to make an OK sign is the classic sign of the latter.",
        presentation: "Clavicle fractures, usually middle third, treated conservatively unless open, tenting the skin or markedly shortened. Proximal humerus fractures in the elderly, usually conservative. Humeral shaft fractures endangering the radial nerve. Supracondylar fractures in children. Distal radius fractures — Colles (dorsal displacement), Smith (volar) and Barton (intra-articular). Scaphoid fractures with snuffbox tenderness.",
        investigations: "Scaphoid views and, if radiographs are normal but clinical suspicion persists, immobilisation and repeat imaging or magnetic resonance imaging, because a missed scaphoid fracture leads to non-union and avascular necrosis. Anterior shoulder dislocation requires documented axillary nerve function before and after reduction; posterior dislocation shows the light-bulb sign and follows seizures and electric shocks.",
        treatment: "Reduce dislocations promptly with adequate analgesia and sedation, then re-image and reassess neurovascular status. Distal radius fractures are reduced and cast, with fixation for unstable, intra-articular or markedly displaced patterns. Supracondylar fractures with displacement need urgent reduction and Kirschner wire fixation, with vascular assessment throughout. Radial nerve palsy with a humeral shaft fracture usually recovers spontaneously.",
      },
      {
        id: "tr_fr_lowerlimb",
        cluster: "Fractures & dislocations (8 marks)",
        name: "Lower limb fractures and dislocations",
        keyFacts: "Posterior knee dislocation and displaced supracondylar femoral fractures threaten the popliteal artery — document pulses, and have a low threshold for angiography, because delayed diagnosis leads to amputation.",
        presentation: "Femoral neck fractures, intracapsular and extracapsular, in the older patient. Femoral shaft fractures, which can lose 1 to 1.5 litres of blood and are associated with fat embolism. Tibial shaft fractures, the commonest site of compartment syndrome and often open because of the subcutaneous anterior surface. Ankle fractures classified by Weber. Calcaneal fractures from axial loading.",
        investigations: "Anteroposterior pelvis and lateral hip views for hip fractures, with cross-sectional imaging for occult fractures. Assess the mortise view for talar shift in ankle injuries. In calcaneal fractures, always examine the lumbar spine and the contralateral limb because of associated injuries. Ottawa ankle and knee rules reduce unnecessary imaging.",
        treatment: "Hip fracture care is protocolised with analgesia including a nerve block, surgery within 36 hours, orthogeriatric input, early mobilisation and bone health assessment. Femoral shaft fractures are stabilised early with an intramedullary nail, which reduces fat embolism and pulmonary complications. Weber A ankle fractures are usually stable and treated conservatively; Weber C are unstable and fixed. Posterior hip dislocation must be reduced urgently to reduce avascular necrosis risk.",
      },
      {
        id: "tr_fr_pelvis",
        cluster: "Fractures & dislocations (8 marks)",
        name: "Pelvic and acetabular fractures",
        keyFacts: "Apply a pelvic binder at the level of the greater trochanters, not the iliac crests — placing it too high fails to close the pelvic ring and does not control bleeding.",
        presentation: "Young and Burgess classification by mechanism: anteroposterior compression (open book, increasing pelvic volume and venous bleeding), lateral compression (commonest, from side impact, often with associated head or abdominal injury), vertical shear (fall from height, most unstable) and combined mechanical injury.",
        investigations: "Anteroposterior pelvic radiograph in the primary survey for the unstable patient; computed tomography for the stable patient and for surgical planning. Look for associated urethral, bladder, rectal and vaginal injury — blood at the meatus, a high-riding prostate, perineal bruising, and blood on rectal or vaginal examination. Do not spring the pelvis repeatedly; it disrupts clot.",
        treatment: "Apply a binder early and do not remove it to obtain films. Bleeding is mostly venous from the presacral plexus and cancellous bone surfaces, so it is controlled by reducing pelvic volume, packing, and angioembolisation for arterial bleeding. Definitive fixation is by external or internal fixation once the patient is stable. Open pelvic fractures with perineal wounds carry very high mortality and may require diverting colostomy.",
      },
      {
        id: "tr_fr_spine",
        cluster: "Fractures & dislocations (8 marks)",
        name: "Spinal injury and spinal cord syndromes",
        keyFacts: "Neurogenic shock is hypotension with bradycardia from loss of sympathetic tone in injuries above T6; spinal shock is the transient flaccid areflexia after cord injury. They are different things and are frequently confused.",
        presentation: "Assume spinal injury in any significant trauma, in the unconscious patient and in the distracted patient, and maintain immobilisation until it is cleared. Examine for tenderness, deformity, motor and sensory levels, reflexes, anal tone and priapism. Document a full American Spinal Injury Association assessment.",
        investigations: "Computed tomography is the primary imaging modality for bony injury; magnetic resonance imaging is used for cord, disc and ligamentous injury and for any neurological deficit. Canadian C-spine and NEXUS rules guide who needs imaging in the alert stable patient. Remember that 10 to 15 per cent of spinal fractures have a second, non-contiguous fracture, so image the whole spine.",
        treatment: "Cord syndromes: complete injury, central cord (arms worse than legs, hyperextension in the elderly), anterior cord (motor and pain and temperature loss with preserved dorsal columns, poor prognosis), Brown-Séquard (hemisection) and cauda equina. Management is avoidance of secondary injury through maintaining oxygenation and perfusion, careful log-rolling and transfers, early specialist referral, pressure area and bladder care, and thromboprophylaxis. High-dose steroids are no longer recommended in acute spinal cord injury.",
      },
      {
        id: "tr_fr_complications",
        cluster: "Fractures & dislocations (8 marks)",
        name: "Complications of fractures",
        keyFacts: "Fat embolism syndrome typically appears 24 to 72 hours after long bone fracture with the triad of hypoxia, petechial rash (axillae, conjunctivae, chest) and confusion.",
        presentation: "Immediate: haemorrhage, neurovascular injury, visceral injury. Early: compartment syndrome, fat embolism, infection, venous thromboembolism, acute respiratory distress syndrome, pressure sores. Late: malunion, delayed union, non-union, avascular necrosis, post-traumatic osteoarthritis, complex regional pain syndrome, heterotopic ossification and growth disturbance in children.",
        investigations: "Delayed union and non-union are diagnosed radiologically with clinical correlation; look for the cause — inadequate stability, poor blood supply, infection, interposed soft tissue, smoking, non-steroidal anti-inflammatory drug use and metabolic bone disease. Complex regional pain syndrome is a clinical diagnosis with disproportionate pain, allodynia, vasomotor and trophic changes.",
        treatment: "Avascular necrosis is common after intracapsular femoral neck, scaphoid proximal pole and talar neck fractures because of their retrograde blood supply. Fat embolism is managed supportively, and prevented by early fracture stabilisation. Complex regional pain syndrome is treated with early mobilisation, physiotherapy and pain team involvement; prolonged immobilisation makes it worse. Prevent thromboembolism, pressure sores and chest complications by mobilising early.",
      },
      {
        id: "tr_fr_paeds",
        cluster: "Fractures & dislocations (8 marks)",
        name: "Paediatric fractures and non-accidental injury",
        keyFacts: "Certain fractures should raise suspicion of non-accidental injury: posterior rib fractures, metaphyseal corner fractures, fractures in a non-ambulant child, multiple fractures of different ages, and any injury inconsistent with the history or developmental stage.",
        presentation: "Children's bones are more elastic with a thicker periosteum, giving greenstick and buckle (torus) fractures. The physis is the weakest point, so ligamentous injuries are less common than physeal ones. Remodelling potential is considerable in the young and near the physis, so more angulation can be accepted, but rotational deformity does not remodel.",
        investigations: "Salter-Harris classification: I through the physis, II with a metaphyseal fragment (commonest), III through the epiphysis into the joint, IV across both, V crush injury with the worst prognosis for growth. Compare with the contralateral side if uncertain. Skeletal survey and safeguarding referral where non-accidental injury is suspected.",
        treatment: "Most paediatric fractures are treated conservatively. Displaced supracondylar fractures need urgent reduction and fixation with careful neurovascular monitoring. If non-accidental injury is suspected, the child's safety comes first: examine fully, document meticulously including body maps, discuss with a senior and the safeguarding team, involve social services, and do not discharge the child until safety is assured. Documentation may become evidence.",
      },

      // ---------------- ORGAN-SPECIFIC TRAUMA (10 marks) ----------------
      {
        id: "tr_org_head",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Head injury and traumatic intracranial haemorrhage",
        keyFacts: "The management of head injury is the prevention of secondary brain injury: avoid hypoxia, hypotension, hypercapnia, hypoglycaemia and hyperglycaemia, pyrexia, hyponatraemia and seizures.",
        presentation: "Assess the Glasgow Coma Scale, pupils and lateralising signs, and re-examine frequently. A fall of 2 or more points, a new focal deficit or a unilateral fixed dilated pupil demands immediate reassessment and imaging. Look for signs of base-of-skull fracture: periorbital or mastoid bruising, cerebrospinal fluid leak and haemotympanum.",
        investigations: "NICE criteria for computed tomography within one hour: Glasgow Coma Scale below 13 on arrival or below 15 at two hours, suspected open or depressed skull fracture, any sign of base-of-skull fracture, post-traumatic seizure, focal neurological deficit, or more than one episode of vomiting. Within eight hours for anticoagulated patients or those with defined risk factors and loss of consciousness or amnesia.",
        treatment: "Extradural haematoma is arterial and biconvex, classically with a lucid interval, and evacuation is urgent. Subdural haematoma is venous and crescentic, commoner in the elderly and in alcohol misuse. Reverse anticoagulation urgently. Measures to control intracranial pressure: head up 30 degrees, neck neutral, sedation and analgesia, normocapnia, osmotherapy and, where indicated, surgical decompression. Discuss every significant head injury with the neurosurgical unit early.",
      },
      {
        id: "tr_org_maxfax",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Maxillofacial trauma and airway compromise",
        keyFacts: "The threat in facial trauma is the airway: bleeding, swelling, displaced fragments and the loss of tongue support in a bilateral mandibular fracture can obstruct it rapidly and unpredictably.",
        presentation: "Le Fort fractures: I transverse across the maxilla above the teeth, II pyramidal involving the nasal bridge, III craniofacial dysjunction. Orbital blow-out fracture causes enophthalmos, diplopia on upward gaze from inferior rectus tethering and infraorbital numbness. Mandibular fractures often occur in pairs because the mandible is a ring.",
        investigations: "Computed tomography of the facial skeleton is the imaging of choice. Assess visual acuity, eye movements and pupillary responses in any periorbital injury, and exclude retrobulbar haemorrhage, which is a sight-threatening emergency. Assess dental occlusion, trismus and any step in the mandible or orbital rim.",
        treatment: "Secure the airway early with senior anaesthetic and, where necessary, surgical airway support — waiting until obstruction is established is dangerous. Control bleeding with packing, reduction of fractures and, rarely, embolisation. Retrobulbar haemorrhage requires immediate lateral canthotomy and cantholysis. Definitive fixation is by open reduction and internal fixation once the airway and other injuries are managed.",
      },
      {
        id: "tr_org_chest",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Thoracic trauma",
        keyFacts: "The immediately life-threatening chest injuries found in the primary survey are airway obstruction, tension pneumothorax, open pneumothorax, massive haemothorax, flail chest with pulmonary contusion, and cardiac tamponade.",
        presentation: "Tension pneumothorax: respiratory distress, hypotension, distended neck veins, tracheal deviation away, absent breath sounds and hyper-resonance — a clinical diagnosis. Massive haemothorax: more than 1500 mL initially or more than 200 mL/h for 2 to 4 hours. Flail chest: paradoxical movement with underlying pulmonary contusion, which is the real problem. Open pneumothorax: a sucking chest wound treated with a three-sided dressing then a chest drain.",
        investigations: "Chest radiograph and extended focused assessment with sonography for trauma in the resuscitation room; computed tomography for the stable patient. A widened mediastinum raises the possibility of aortic injury at the ligamentum arteriosum, confirmed by computed tomography angiography. Serial gases and monitoring for evolving contusion.",
        treatment: "Chest drain for pneumothorax and haemothorax, inserted in the safe triangle. Indications for thoracotomy: initial drainage over 1500 mL, continued loss over 200 mL/h, cardiac tamponade, massive air leak and great vessel injury. Rib fractures need excellent analgesia including regional blocks to prevent atelectasis and pneumonia, particularly in the elderly. Pulmonary contusion evolves over 24 to 48 hours and is managed with careful fluid balance and respiratory support.",
      },
      {
        id: "tr_org_cardiac",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Cardiac and great vessel injury",
        keyFacts: "Beck's triad of hypotension, raised jugular venous pressure and muffled heart sounds is present in a minority of tamponade cases; a high index of suspicion in penetrating chest trauma matters more than the triad.",
        presentation: "Penetrating injury in the cardiac box (between the midclavicular lines, from the clavicles to the costal margins) raises the possibility of cardiac injury. Blunt cardiac injury causes arrhythmia, contusion and rarely valve or septal rupture. Traumatic aortic injury classically occurs at the isthmus near the ligamentum arteriosum in deceleration injury.",
        investigations: "Extended focused assessment with sonography for trauma detects pericardial fluid rapidly. Electrocardiogram and troponin for suspected blunt cardiac injury. Computed tomography angiography for suspected aortic injury in the stable patient — signs on chest radiograph include a widened mediastinum, loss of the aortic knuckle, a left apical cap and deviation of the nasogastric tube.",
        treatment: "Tamponade is relieved definitively by surgery; pericardiocentesis is a temporising measure. Resuscitative thoracotomy has a role in penetrating chest trauma with witnessed loss of output and a short down time, and much less in blunt trauma. Traumatic aortic injury is increasingly managed by endovascular repair, with blood pressure and heart rate control while awaiting definitive treatment.",
      },
      {
        id: "tr_org_abdo",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Blunt and penetrating abdominal trauma",
        keyFacts: "The spleen is the most commonly injured organ in blunt abdominal trauma, and the liver the most commonly injured in penetrating trauma. A negative focused assessment with sonography for trauma does not exclude significant injury.",
        presentation: "Abdominal examination is unreliable in the unconscious, the intoxicated and those with distracting injuries or spinal cord injury. Look for seat-belt marks, bruising, distension and tenderness. Delayed splenic rupture can occur days after injury as a subcapsular haematoma expands.",
        investigations: "Focused assessment with sonography for trauma in the unstable patient images the hepatorenal recess, the perisplenic space, the pelvis and the pericardium. Computed tomography with contrast is the investigation of choice in the stable patient and grades solid organ injury. Diagnostic peritoneal lavage is now rarely used. Penetrating anterior abdominal stab wounds may be assessed by local wound exploration, serial examination or laparoscopy.",
        treatment: "Non-operative management of solid organ injury is now standard in the haemodynamically stable patient with appropriate monitoring and access to angioembolisation. Indications for laparotomy: haemodynamic instability with a positive focused assessment, peritonitis, evisceration, free gas, gunshot wounds crossing the peritoneum, and failure of non-operative management. Splenectomy mandates lifelong vaccination and prophylaxis against encapsulated organisms.",
      },
      {
        id: "tr_org_liver_spleen",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Hepatic and splenic trauma",
        keyFacts: "The Pringle manoeuvre clamps the portal triad at the epiploic foramen to control inflow; if bleeding continues despite it, the source is hepatic venous or inferior vena caval and the situation is far more serious.",
        presentation: "Splenic injury causes left upper quadrant pain and referred left shoulder-tip pain (Kehr sign) from diaphragmatic irritation. Hepatic injury causes right upper quadrant pain and may present with a slow bleed or with massive haemorrhage from the retrohepatic veins. Both are graded by the American Association for the Surgery of Trauma scale.",
        investigations: "Computed tomography with contrast grades the injury and detects contrast blush indicating active bleeding suitable for angioembolisation. Serial haemoglobin and observation in a monitored setting are the mainstays of non-operative management. Repeat imaging if the patient deteriorates or fails to improve.",
        treatment: "Non-operative management succeeds in the majority of stable patients and preserves splenic immune function. Angioembolisation extends the range of injuries that can be managed without surgery. Operative options: splenorrhaphy or splenectomy; for the liver, packing, direct suture, selective ligation and, rarely, resection — with packing and damage control the safest choice for the inexperienced. Post-splenectomy sepsis prophylaxis must be arranged before discharge.",
      },
      {
        id: "tr_org_urogenital",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Urogenital trauma",
        keyFacts: "Blood at the urethral meatus, a high-riding prostate or perineal bruising after pelvic trauma contraindicates urethral catheterisation until a retrograde urethrogram has been performed.",
        presentation: "Renal injury presents with loin pain, flank bruising and haematuria, though the degree of haematuria does not correlate with severity and can be absent in pedicle injury. Bladder injury follows pelvic fracture or a blow to the full bladder. Urethral injury is bulbar in straddle injuries and membranous in pelvic fractures.",
        investigations: "Computed tomography with delayed (excretory) phase images the renal tract. Retrograde urethrogram for suspected urethral injury; cystogram for suspected bladder rupture. Assess for associated injuries, since isolated urological trauma is uncommon in major mechanisms.",
        treatment: "Most renal injuries are managed non-operatively; indications for exploration are haemodynamic instability, an expanding or pulsatile perirenal haematoma and renal pedicle avulsion. Intraperitoneal bladder rupture requires operative repair; extraperitoneal rupture is usually managed with catheter drainage. Urethral injury requires urological involvement, with suprapubic diversion where catheterisation is unsafe. Testicular rupture requires exploration and repair.",
      },
      {
        id: "tr_org_vascular",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Vascular injury and iatrogenic trauma",
        keyFacts: "Hard signs of arterial injury — pulsatile bleeding, an expanding haematoma, a palpable thrill or audible bruit, absent distal pulses and signs of distal ischaemia — mandate immediate exploration without further imaging.",
        presentation: "Soft signs are a history of significant bleeding, a non-expanding haematoma, proximity of the wound to a major vessel, an unexplained neurological deficit and a diminished pulse. Iatrogenic vascular injury is now a common cause, from arterial access, central lines, laparoscopic ports and orthopaedic instrumentation.",
        investigations: "Compare pulses and measure the injured extremity index. Computed tomography angiography where soft signs are present or the anatomy is unclear. Do not delay revascularisation in a limb with hard signs; the ischaemic time is what determines outcome, with about six hours the usual limit before irreversible muscle injury.",
        treatment: "Control haemorrhage with direct pressure or a tourniquet, resuscitate with blood products, and involve vascular surgery immediately. Options include direct repair, patch, interposition graft (using reversed vein rather than prosthetic in a contaminated field) and temporary shunting in damage control. Consider fasciotomy after prolonged ischaemia. Intravascular drug use causes pseudoaneurysm and infected groin haematoma, which are hazardous and often require ligation.",
      },
      {
        id: "tr_org_nerve",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Peripheral nerve injury in trauma",
        keyFacts: "Seddon's classification: neurapraxia (conduction block, full recovery), axonotmesis (axonal disruption with an intact endoneurial sheath, recovering at about 1 mm per day) and neurotmesis (complete transection, requiring surgical repair).",
        presentation: "Document motor and sensory function distal to every injury before and after any manipulation or splintage. Common associations: axillary nerve with shoulder dislocation, radial nerve with humeral shaft fracture, median and anterior interosseous nerve with supracondylar fracture, sciatic nerve with posterior hip dislocation, and common peroneal nerve with fibular neck fracture or knee dislocation.",
        investigations: "Clinical examination repeated over time is the mainstay. Nerve conduction studies and electromyography at about three weeks distinguish the types and establish a baseline. An advancing Tinel sign indicates regeneration. Ultrasound and magnetic resonance imaging can demonstrate nerve continuity.",
        treatment: "Sharp clean transections are repaired primarily with epineurial sutures; contaminated or ragged injuries are tagged and repaired at a delayed second procedure. Closed injuries associated with fractures usually recover and are observed. Physiotherapy, splinting to prevent contracture and protection of anaesthetic skin are essential throughout. Refer to a specialist peripheral nerve service if there is no recovery by the expected time.",
      },
      {
        id: "tr_org_skinloss",
        cluster: "Organ-specific trauma (10 marks)",
        name: "Skin loss, grafts and flaps",
        keyFacts: "The reconstructive ladder runs from secondary intention, through direct closure, split-thickness graft, full-thickness graft, local flap, regional flap and free tissue transfer — climb only as high as the defect requires.",
        presentation: "Assess the defect for its size, depth, contamination, the state of the wound bed, exposed structures and the functional and cosmetic requirements of the site. A wound with exposed bone without periosteum, cartilage without perichondrium or tendon without paratenon will not accept a graft.",
        investigations: "Assess perfusion of the wound bed and the planned donor site, and the patient's overall fitness for a prolonged reconstructive procedure. Photography is invaluable for planning, for the multidisciplinary discussion and for documentation. Debridement quality determines graft take more than any other factor.",
        treatment: "Split-thickness grafts take epidermis and part of the dermis, cover large areas, can be meshed, and the donor site heals from retained appendages; they contract more and match colour less well. Full-thickness grafts give better cosmesis and less contraction but require a smaller defect and closure of the donor site. Grafts take by imbibition, inosculation and revascularisation, so shear, haematoma and infection are the enemies. Flaps carry their own blood supply and are needed for exposed bone, tendon, joint or implant.",
      },
    ],
  },

  {
    id: "paeds",
    name: "Surgical Care of Children",
    short: "Paediatrics",
    icon: "👶",
    paper: "paper2",
    marks: 7,
    itemNoun: "topics",
    fieldLabels: ["👶 Presentation", "🔬 Investigations", "💊 Management"],
    blurb: "Seven marks covering the conditions and the safeguarding framework every core trainee is expected to know. Small enough to clear completely in a fortnight, which makes it excellent value in Phase 3.",
    conditions: [
      {
        id: "pd_physiology",
        cluster: "Principles of paediatric surgical care",
        name: "Paediatric physiology, fluids and safe prescribing",
        keyFacts: "Children have a larger surface-area-to-volume ratio, higher metabolic rate and smaller glycogen stores, so they become hypothermic, dehydrated and hypoglycaemic much faster than adults.",
        presentation: "Normal parameters change with age: a neonate has a heart rate of 110 to 160 and a respiratory rate of 30 to 60, whereas a twelve-year-old approaches adult values. Blood volume is about 80 mL/kg in children and 90 mL/kg in neonates, so small absolute losses are proportionately large.",
        investigations: "Estimate weight by a length-based tape or an age-based formula, and calculate every dose and fluid volume by weight. Maintenance fluid uses the 4-2-1 rule: 4 mL/kg/h for the first 10 kg, 2 mL/kg/h for the next 10 kg and 1 mL/kg/h thereafter, using an isotonic solution with glucose to avoid hyponatraemia.",
        treatment: "Resuscitation fluid is 10 mL/kg boluses of a balanced crystalloid, moving early to blood in trauma. Avoid hypotonic maintenance fluids, which have caused fatal hyponatraemia. Prescribe by weight, check every calculation, and recognise the limits of your own experience — the syllabus explicitly requires trainees to seek early advice from paediatric teams.",
      },
      {
        id: "pd_pyloric",
        cluster: "Common paediatric conditions",
        name: "Infantile hypertrophic pyloric stenosis",
        keyFacts: "Pyloric stenosis causes a hypochloraemic, hypokalaemic metabolic alkalosis with paradoxical aciduria — and it is a medical emergency requiring correction before anaesthesia, not a surgical emergency.",
        presentation: "Typically a first-born male at three to six weeks of age with progressive non-bilious projectile vomiting after feeds, remaining hungry afterwards. Signs include visible gastric peristalsis, dehydration, weight loss and a palpable olive-shaped mass in the right upper quadrant during a test feed.",
        investigations: "Ultrasound is diagnostic, showing a thickened elongated pylorus. Blood gases and electrolytes demonstrate the characteristic alkalosis with low chloride and potassium. Bilious vomiting is not pyloric stenosis and should prompt urgent assessment for malrotation with volvulus.",
        treatment: "Resuscitate and correct the electrolyte and acid-base abnormality with 0.9 per cent sodium chloride and added potassium before any operation, because alkalosis causes postoperative apnoea. Once corrected, perform a Ramstedt pyloromyotomy, dividing the hypertrophied muscle without breaching the mucosa. Feeding resumes within hours and the prognosis is excellent.",
      },
      {
        id: "pd_intussusception",
        cluster: "Common paediatric conditions",
        name: "Intussusception and paediatric abdominal pain",
        keyFacts: "Intussusception classically affects infants of six months to two years with intermittent colic, drawing up the legs, a sausage-shaped mass and redcurrant jelly stool — but the stool is a late sign and its absence does not exclude the diagnosis.",
        presentation: "Episodic severe colic with pallor and screaming, with the child appearing well or lethargic between episodes. Vomiting, which may become bilious. Ileocolic is the commonest type, usually idiopathic and related to lymphoid hyperplasia after a viral illness; a pathological lead point such as a Meckel's diverticulum or polyp is more likely in older children.",
        investigations: "Ultrasound shows the target or doughnut sign and is the investigation of choice. Assess hydration and resuscitate. Consider the differential of malrotation with volvulus, appendicitis, incarcerated hernia, constipation, gastroenteritis, Henoch-Schönlein purpura and, in the neonate, necrotising enterocolitis.",
        treatment: "Resuscitate first, then reduce by air or contrast enema in the absence of peritonitis or perforation, with surgical cover available. Operative reduction is required if enema fails, if there is peritonitis or perforation, or if a pathological lead point is suspected. Recurrence occurs in a minority. Bilious vomiting in an infant is malrotation with midgut volvulus until proved otherwise and requires urgent upper gastrointestinal contrast study and Ladd's procedure.",
      },
      {
        id: "pd_groin",
        cluster: "Common paediatric conditions",
        name: "Inguinal hernia, hydrocele, undescended testis and phimosis",
        keyFacts: "In children the pathology is a patent processus vaginalis, so herniotomy — simple ligation of the sac — is sufficient and mesh is never used.",
        presentation: "Paediatric inguinal hernia is indirect, commoner in boys and in the premature, and presents as an intermittent groin swelling. Incarceration is much more common than in adults, particularly in the first year. Communicating hydrocele varies in size through the day and transilluminates. Undescended testis is impalpable or palpable in the canal. Phimosis is non-retractile foreskin, which is physiological in early childhood.",
        investigations: "Diagnosis is clinical. Ultrasound may help locate a palpable undescended testis but laparoscopy is required for an impalpable one. Distinguish a retractile testis, which needs no surgery, from a truly undescended one. Assess for hypospadias and other genital anomalies, and consider disorders of sex development if bilateral impalpable testes are present.",
        treatment: "Paediatric inguinal hernia is repaired promptly because of the incarceration risk, particularly urgently in infants. Incarcerated hernia should be reduced with sedation and gentle taxis then repaired on the same admission. Hydroceles usually resolve by two years and are not repaired before then. Orchidopexy is recommended between six and twelve months to improve fertility and permit examination, though the increased malignancy risk is not abolished. Circumcision is indicated for pathological phimosis such as balanitis xerotica obliterans, recurrent balanoposthitis and recurrent urinary tract infection, and is contraindicated in hypospadias where the foreskin is needed for reconstruction.",
      },
      {
        id: "pd_neonatal",
        cluster: "Common paediatric conditions",
        name: "Neonatal surgical emergencies and congenital anomalies",
        keyFacts: "Bilious vomiting in a neonate is a surgical emergency — malrotation with midgut volvulus until proved otherwise — and delay costs the entire midgut.",
        presentation: "Oesophageal atresia with tracheo-oesophageal fistula: excessive secretions, choking on feeding and inability to pass a nasogastric tube. Duodenal atresia: bilious vomiting with the double bubble sign, associated with Down syndrome. Hirschsprung disease: delayed passage of meconium beyond 48 hours, distension and enterocolitis. Necrotising enterocolitis in the preterm infant: feed intolerance, distension, bloody stool and pneumatosis intestinalis.",
        investigations: "Plain abdominal radiograph, upper gastrointestinal contrast study for suspected malrotation, and suction rectal biopsy for Hirschsprung disease. Look for associated anomalies: the VACTERL association covers vertebral, anorectal, cardiac, tracheo-oesophageal, renal and limb defects, so finding one mandates a search for the others.",
        treatment: "Resuscitate, keep warm, decompress the stomach, give intravenous fluids and antibiotics as indicated, and transfer urgently to a paediatric surgical centre. Congenital diaphragmatic hernia is a physiological rather than a surgical emergency: stabilise the infant, avoid bag-mask ventilation which distends the herniated bowel, and operate once stable. Exomphalos is covered by a sac and associated with other anomalies; gastroschisis is uncovered and requires urgent bowel protection and fluid resuscitation.",
      },
      {
        id: "pd_safeguarding",
        cluster: "Safeguarding & consent",
        name: "Child protection and safeguarding",
        keyFacts: "The child's welfare is paramount. If you suspect maltreatment, the child's safety comes before the professional relationship with the family and before concerns about being wrong.",
        presentation: "Categories of maltreatment: physical abuse, emotional abuse, sexual abuse and neglect, plus fabricated or induced illness. Warning features include a history inconsistent with the injury or the child's developmental stage, a changing or absent history, delayed presentation, inappropriate parental behaviour, and the child's demeanour.",
        investigations: "Suspicious injuries include bruising in a non-mobile infant, bruising of unusual sites such as the ears, neck and buttocks, cigarette burns, immersion scald patterns, torn frenulum, posterior rib and metaphyseal corner fractures, and fractures of different ages. Document findings precisely with body maps, measurements and, where protocol allows, photography. Check whether the child is already known to social services.",
        treatment: "Follow the local safeguarding procedure: discuss with a senior colleague and the named safeguarding professional immediately, refer to social services, and admit the child if their safety cannot otherwise be assured. Share information appropriately — safeguarding overrides ordinary confidentiality. Record contemporaneously, factually and legibly, because your notes may become evidence.",
      },
      {
        id: "pd_consent",
        cluster: "Safeguarding & consent",
        name: "Consent in children and communication with families",
        keyFacts: "A competent child aged 16 or 17 is presumed able to consent to treatment; a child under 16 may consent if Gillick competent. Refusal by a competent minor can, in some circumstances, be overridden by those with parental responsibility or by the court, which is not true of adults.",
        presentation: "Parental responsibility is held by the mother automatically, by the father if married to the mother at the time of birth or named on the birth certificate after December 2003, and by others through court order or agreement. Only one person with parental responsibility need consent, but significant disagreement should prompt legal advice.",
        investigations: "Assess Gillick competence for the specific decision: does the child understand the nature, purpose, risks, benefits and alternatives, and can they weigh and communicate a decision? Involve children in decisions about their care to the extent they are able, regardless of formal competence.",
        treatment: "Communicate with the child at their level as well as with the parents, use play specialists and allow parental presence at induction where possible. In an emergency where nobody with parental responsibility is available, necessary treatment may proceed under the doctrine of necessity. Document who gave consent, their relationship and their parental responsibility status.",
      },
    ],
  },

  {
    id: "profpractice",
    name: "Professional Practice, Ethics & Transplantation",
    short: "Professional",
    icon: "⚖️",
    paper: "paper2",
    marks: 3,
    itemNoun: "topics",
    fieldLabels: ["⚖️ Principle", "📋 In practice", "📝 Exam angle"],
    blurb: "Three medico-legal marks in the blueprint, but this section also carries syllabus Modules 8, 9 and 10 — the dying patient, transplantation, and professional behaviour and leadership. Reliably scoreable if you know the frameworks.",
    conditions: [
      {
        id: "pp_ethics",
        cluster: "Ethics & law",
        name: "Ethical principles, confidentiality and duty of candour",
        keyFacts: "The four principles are autonomy, beneficence, non-maleficence and justice. When they conflict — as they usually do in an examination question — autonomy of a competent adult generally takes precedence.",
        presentation: "Confidentiality is a professional and legal duty but is not absolute. Disclosure without consent is justified where required by law (notifiable diseases, court order, the Road Traffic Act), or in the public interest where the risk of serious harm to others outweighs the duty — for example an unfit driver who continues to drive after being advised not to.",
        investigations: "Duty of candour requires that patients are told promptly when something has gone wrong that has caused or could cause harm, that an apology is offered, and that an explanation is given of what will be done. This is both a professional duty under Good Medical Practice and a statutory duty for organisations.",
        treatment: "Raising concerns about a colleague or a system is a professional obligation, not an option; the General Medical Council expects doctors to act promptly where patient safety is at risk, and there are legal protections for those who do so in good faith. Consent, capacity and best interests are covered in the perioperative section and are the commonest medico-legal examination topics alongside confidentiality.",
      },
      {
        id: "pp_death",
        cluster: "The dying patient",
        name: "Management of the dying patient, DNACPR and certification",
        keyFacts: "A do not attempt cardiopulmonary resuscitation decision concerns one intervention only. It must be discussed with the patient, or their advocate if they lack capacity, and never means withdrawing other treatment or care.",
        presentation: "Recognise dying: progressive irreversible deterioration, reduced consciousness, reduced oral intake, peripheral shutdown and changing respiratory pattern. Anticipate pain, breathlessness, nausea, agitation and respiratory secretions, and prescribe for them in advance.",
        investigations: "Stop investigations and observations that will not change management and document that decision. Review medication, stopping what no longer serves comfort and converting what does to a suitable route. Involve the specialist palliative care team early rather than at the very end.",
        treatment: "Certification of death requires the doctor to have attended during the last illness and to state the cause to the best of their knowledge. Referral to the coroner is required for deaths that are unexpected, violent or unnatural, related to an accident, injury or industrial disease, occurring during or shortly after an operation or anaesthetic, where the cause is unknown, or where no attending doctor can certify. Cremation forms carry additional requirements. Discuss organ and tissue donation with the specialist nurse for organ donation before approaching the family.",
      },
      {
        id: "pp_transplant",
        cluster: "Transplantation",
        name: "Organ and tissue transplantation",
        keyFacts: "England, Wales and Scotland now operate an opt-out (deemed consent) system for organ donation, but the family is always consulted and donation does not proceed against their strongly held wishes in practice.",
        presentation: "Donor categories: donation after brainstem death, donation after circulatory death, and living donation (related, unrelated and paired or pooled). Tissue donation — cornea, skin, bone, heart valves and tendon — is possible from a much wider range of donors and for longer after death.",
        investigations: "Brainstem death testing requires strict preconditions: an established irreversible cause of coma, and exclusion of hypothermia, drug effects and severe metabolic or endocrine disturbance. Two suitably experienced doctors, at least one a consultant and both registered for more than five years, perform two sets of tests examining the pupillary, corneal, oculovestibular, oculocephalic, gag and cough reflexes, plus an apnoea test.",
        treatment: "Transplant immunology and immunosuppression are covered in the pathology section. Cold ischaemia time influences graft function and differs by organ, the kidney tolerating it best. Complications of immunosuppression are infection, malignancy (especially skin cancer and post-transplant lymphoproliferative disease), nephrotoxicity, diabetes and hypertension. Any transplant recipient presenting acutely should be discussed early with their transplant centre.",
      },
      {
        id: "pp_leadership",
        cluster: "Professional behaviour & leadership",
        name: "Teamworking, human factors and clinical governance",
        keyFacts: "Most surgical error is not technical: it arises from communication failure, hierarchy, distraction, fatigue and poor situational awareness — which is why the checklist, briefing and debriefing exist.",
        presentation: "Non-technical skills for surgeons cover situation awareness, decision making, communication and teamwork, and leadership. Structured communication tools such as SBAR (situation, background, assessment, recommendation) improve handover and escalation. Graded assertiveness allows a junior member to escalate a concern effectively.",
        investigations: "Clinical governance pillars: clinical effectiveness, audit, risk management, education and training, patient and public involvement, information management, and staffing and staff management. Incident reporting, morbidity and mortality meetings, national audits and confidential enquiries provide system-level learning.",
        treatment: "When something goes wrong: stabilise the patient, inform your consultant, document factually and contemporaneously, report through the incident system, comply with the duty of candour and support the staff involved. Quality improvement uses plan-do-study-act cycles. Never events such as wrong-site surgery and retained foreign objects are investigated formally, and the response should focus on the system rather than on individual blame.",
      },
      {
        id: "pp_health",
        cluster: "Health promotion",
        name: "Health promotion, obesity, dementia and physical fitness",
        keyFacts: "The ISCP health promotion module expects surgeons to use every patient contact as an opportunity for health promotion — smoking cessation before surgery is the single highest-value intervention a surgeon can make.",
        presentation: "Obesity classification by body mass index: overweight 25 to 29.9, obese class I 30 to 34.9, class II 35 to 39.9, class III 40 or more. Obesity increases the risks of coronary heart disease, type 2 diabetes, hypertension, stroke and several cancers, and complicates every aspect of surgical care from access to positioning to wound healing.",
        investigations: "Screen for alcohol use, smoking and physical inactivity as routinely as for allergies. Recognise cognitive impairment and distinguish dementia from delirium, since delirium is common in people with dementia and both change perioperative planning. Assess capacity where cognition is impaired and involve advocates.",
        treatment: "Offer smoking cessation support at every surgical contact; stopping for four to eight weeks before surgery reduces pulmonary and wound complications. Treat obese patients supportively and without judgement, explain the specific increased risks honestly, and involve the multidisciplinary team for weight management. Communicate with people with dementia using clear, unhurried, familiar language, involve carers, and document capacity assessments and best-interests decisions properly.",
      },
    ],
  },
];
